(window.FRAMEWORKS = window.FRAMEWORKS || []).push({
  id: "pyside",
  name: "PySide6 (Qt)",
  language: "Python",
  group: "Python",
  navLabel: "PySide6 (Qt)",
  color: "#41cd52",
  readMinutes: 30,
  tagline: "**Qt 6 for Python** — build real native desktop apps with widgets, **signals & slots**, model/view, threading and QSS styling. Official bindings (`pip install PySide6`), LGPL.",

  sections: [
    {
      id: "overview",
      title: "Overview: Qt for Python, PySide6 vs PyQt6",
      level: "core",
      body: [
        { type: "p", text: "**Qt** is a mature C++ cross-platform application framework (widgets, event loop, networking, painting, multimedia). **Qt for Python** exposes it to Python. Two competing binding sets wrap the *same* Qt libraries with near-identical APIs — the code you write is ~95% the same either way." },
        { type: "table", headers: ["", "PySide6", "PyQt6"], rows: [
          ["Maintainer", "The Qt Company (official)", "Riverbank Computing (third party)"],
          ["License", "**LGPL v3** (usable in closed-source apps if you dynamically link) + commercial", "**GPL v3** or a paid commercial license — no free closed-source use"],
          ["Signal/slot names", "`Signal`, `Slot`, `Property`", "`pyqtSignal`, `pyqtSlot`, `pyqtProperty`"],
          ["`.exec()`", "`app.exec()` (also `exec_()` alias)", "`app.exec()` (Qt6 dropped `exec_`)"],
          ["Enums", "scoped: `Qt.AlignmentFlag.AlignCenter`", "scoped: `Qt.AlignmentFlag.AlignCenter`"],
          ["Import", "`from PySide6.QtWidgets import ...`", "`from PyQt6.QtWidgets import ...`"]
        ] },
        { type: "p", text: "**Choose PySide6** unless you have a specific reason not to: it is the *official* binding, LGPL (so you can ship proprietary apps without buying a license), and backed by the Qt Company's release cadence. **PyQt6** is older, extremely stable, and some legacy codebases/tutorials use it — but its GPL license forces you to either open-source your app or buy a commercial license. This deck targets **PySide6 / Qt 6** on **Python 3.12+**." },
        { type: "heading", text: "Qt Widgets vs Qt Quick (QML)" },
        { type: "list", items: [
          "**Qt Widgets** — the classic, imperative toolkit (`QPushButton`, `QMainWindow`, layouts). Native look-and-feel, huge widget set, ideal for **data-dense desktop tools** (IDEs, dashboards, forms). This is the main focus of this deck.",
          "**Qt Quick / QML** — a declarative UI language (JSON-ish) with a JavaScript-like binding syntax, GPU-accelerated, animation-first. Better for **touch UIs, mobile, embedded, and fluid custom-designed interfaces**. You wire Python business logic behind a QML front end.",
          "You can mix them, but pick one as the primary UI paradigm per window. For a traditional desktop app, start with Widgets."
        ] },
        { type: "callout", variant: "note", text: "Bindings are generated by **shiboken6**, Qt's binding generator. It also lets you bind your own C++ into Python. When an error mentions `Shiboken`, it is the C++/Python marshalling layer talking." },
        { type: "callout", variant: "tip", text: "Porting PyQt tutorials to PySide is mostly mechanical: rename `pyqtSignal`→`Signal`, `pyqtSlot`→`Slot`, and check enum spellings. The widget APIs are identical because both wrap the same Qt." }
      ]
    },
    {
      id: "setup",
      title: "Setup & your first app",
      level: "core",
      body: [
        { type: "p", text: "PySide6 ships as a single wheel containing the Qt libraries — no separate Qt install needed. Use a virtualenv." },
        { type: "code", lang: "bash", code: "python -m venv .venv\nsource .venv/bin/activate        # Windows: .venv\\Scripts\\activate\n\npip install PySide6              # pulls in shiboken6 + all Qt6 modules\npython -c \"import PySide6; print(PySide6.__version__)\"   # e.g. 6.9.x\n\n# handy CLI tools that come with the wheel:\npyside6-designer                 # the visual UI editor (Qt Designer)\npyside6-uic form.ui -o ui_form.py  # compile a .ui to Python\npyside6-rcc res.qrc -o rc_res.py   # compile a resource file" },
        { type: "p", text: "The minimal app: create **one** `QApplication`, build a top-level widget, `show()` it, then hand control to Qt's event loop with `app.exec()`. Nothing renders until the event loop runs." },
        { type: "code", lang: "python", code: "import sys\nfrom PySide6.QtWidgets import QApplication, QWidget, QLabel, QVBoxLayout\n\napp = QApplication(sys.argv)          # exactly ONE per process; pass argv for Qt flags\n\nwindow = QWidget()                    # a bare top-level window\nwindow.setWindowTitle(\"Hello PySide6\")\nwindow.resize(320, 120)\n\nlayout = QVBoxLayout(window)          # passing the parent applies it immediately\nlayout.addWidget(QLabel(\"It works.\"))\n\nwindow.show()                         # widgets are hidden until you show() them\nsys.exit(app.exec())                  # blocks here, runs the event loop, returns exit code" },
        { type: "p", text: "For a real app you subclass `QMainWindow` (or `QWidget`) so each window is a self-contained class. Note the `super().__init__()` call — forget it and Qt's C++ object is never initialized and you get cryptic crashes." },
        { type: "code", lang: "python", code: "import sys\nfrom PySide6.QtWidgets import QApplication, QMainWindow, QPushButton\n\nclass MainWindow(QMainWindow):\n    def __init__(self):\n        super().__init__()            # MUST call this first\n        self.setWindowTitle(\"My App\")\n        button = QPushButton(\"Click me\")\n        button.clicked.connect(self.on_click)\n        self.setCentralWidget(button)\n\n    def on_click(self):\n        print(\"clicked\")\n\nif __name__ == \"__main__\":\n    app = QApplication(sys.argv)\n    win = MainWindow()\n    win.show()\n    sys.exit(app.exec())" },
        { type: "callout", variant: "gotcha", text: "Create the `QApplication` **before** any widget. Constructing a `QWidget` with no running `QApplication` crashes hard (`QWidget: Must construct a QApplication before a QWidget`)." }
      ]
    },
    {
      id: "widgets",
      title: "Widget tour: the building blocks",
      level: "core",
      body: [
        { type: "p", text: "Widgets are the visible controls. Every widget is a `QWidget` subclass; any widget can be a window (top-level) or a child. Here are the ones you reach for daily." },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import (\n    QLabel, QPushButton, QLineEdit, QTextEdit, QComboBox, QCheckBox,\n    QRadioButton, QSlider, QSpinBox, QListWidget, QTableWidget,\n    QTableWidgetItem, QTreeWidget, QTreeWidgetItem, QTabWidget, QGroupBox,\n)\nfrom PySide6.QtCore import Qt\n\nlabel   = QLabel(\"Static or <b>rich</b> text\")   # supports a subset of HTML\nbutton  = QPushButton(\"Save\")\nline    = QLineEdit(); line.setPlaceholderText(\"search...\")\nline.setEchoMode(QLineEdit.EchoMode.Password)     # masked input\nbig     = QTextEdit()                              # multi-line, rich text\ncombo   = QComboBox(); combo.addItems([\"Red\", \"Green\", \"Blue\"])\ncheck   = QCheckBox(\"Enabled\"); check.setChecked(True)\nradio   = QRadioButton(\"Option A\")                 # group radios in a QButtonGroup\nslider  = QSlider(Qt.Orientation.Horizontal); slider.setRange(0, 100)\nspin    = QSpinBox(); spin.setRange(0, 10); spin.setValue(3)" },
        { type: "heading", text: "Item widgets: lists, tables, trees" },
        { type: "code", lang: "python", code: "# QListWidget — simple flat list\nlst = QListWidget()\nlst.addItems([\"Alice\", \"Bob\", \"Carol\"])\n\n# QTableWidget — grid of QTableWidgetItem cells\ntable = QTableWidget(2, 3)                          # rows, cols\ntable.setHorizontalHeaderLabels([\"Name\", \"Age\", \"City\"])\ntable.setItem(0, 0, QTableWidgetItem(\"Alice\"))\ntable.setItem(0, 1, QTableWidgetItem(\"30\"))\n\n# QTreeWidget — hierarchical rows\ntree = QTreeWidget(); tree.setHeaderLabels([\"Item\", \"Value\"])\nroot = QTreeWidgetItem(tree, [\"Fruit\", \"\"])\nQTreeWidgetItem(root, [\"Apple\", \"3\"])\ntree.expandAll()" },
        { type: "heading", text: "Grouping: tabs & group boxes" },
        { type: "code", lang: "python", code: "tabs = QTabWidget()\ntabs.addTab(some_widget, \"General\")\ntabs.addTab(other_widget, \"Advanced\")\n\ngroup = QGroupBox(\"Connection\")     # titled, bordered container (give it a layout)\n# group.setLayout(form_layout)" },
        { type: "callout", variant: "note", text: "The `*Widget` classes (`QListWidget`, `QTableWidget`, `QTreeWidget`) are the *convenience* item-based views — great for small, static data. For large or dynamic datasets, use the **model/view** classes (`QListView`/`QTableView` + a model) covered later. Don't stuff 100k `QTableWidgetItem`s into a `QTableWidget`." },
        { type: "callout", variant: "tip", text: "`widget.setToolTip(...)`, `setEnabled(False)`, `setVisible(False)`, and `setObjectName(\"saveBtn\")` (for QSS/testing) exist on every widget. `setFocus()` and `setFocusPolicy(...)` control keyboard focus." }
      ]
    },
    {
      id: "layouts",
      title: "Layouts: never use absolute positions",
      level: "core",
      body: [
        { type: "p", text: "You almost never set fixed pixel coordinates. **Layout managers** arrange child widgets, resize them with the window, and handle DPI scaling. A widget gets a layout; the layout holds widgets (and nested layouts)." },
        { type: "table", headers: ["Layout", "Arranges children"], rows: [
          ["`QVBoxLayout`", "vertically, top to bottom"],
          ["`QHBoxLayout`", "horizontally, left to right"],
          ["`QGridLayout`", "in a row/column grid (spanning cells allowed)"],
          ["`QFormLayout`", "two columns: label + field rows (ideal for forms)"],
          ["`QStackedLayout`", "one child visible at a time (like tabs without the bar)"]
        ] },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import (\n    QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QFormLayout,\n    QPushButton, QLabel, QLineEdit,\n)\n\nroot = QWidget()\nouter = QVBoxLayout(root)              # attach layout to root at construction\n\n# a form section\nform = QFormLayout()\nform.addRow(\"Name:\", QLineEdit())      # label text + field, laid out in two columns\nform.addRow(\"Email:\", QLineEdit())\nouter.addLayout(form)                  # NEST a layout inside another\n\n# a row of buttons pushed to the right\nrow = QHBoxLayout()\nrow.addStretch()                       # elastic spacer: eats leftover space\nrow.addWidget(QPushButton(\"Cancel\"))\nrow.addWidget(QPushButton(\"OK\"))\nouter.addLayout(row)\n\n# a grid: addWidget(widget, row, col, rowSpan=1, colSpan=1)\ngrid = QGridLayout()\ngrid.addWidget(QLabel(\"A\"), 0, 0)\ngrid.addWidget(QLabel(\"B\"), 0, 1)\ngrid.addWidget(QPushButton(\"Wide\"), 1, 0, 1, 2)   # spans 2 columns\nouter.addLayout(grid)" },
        { type: "list", items: [
          "**`addStretch()`** inserts a stretchable spacer — the classic way to push widgets to one side or center them. **`addSpacing(px)`** adds a fixed gap.",
          "**Stretch factors:** `layout.addWidget(w, stretch=2)` gives `w` twice the growth of a `stretch=1` sibling when the window resizes.",
          "**`setContentsMargins(l, t, r, b)`** and **`setSpacing(px)`** tune the padding around and between items.",
          "Use **`addWidget`** for widgets and **`addLayout`** for nested layouts — mixing them up is a common mistake.",
          "**Size policy** (`widget.setSizePolicy(...)`) tells the layout whether a widget can grow/shrink; `setFixedWidth/Height` locks a dimension."
        ] },
        { type: "callout", variant: "gotcha", text: "If your widgets pile up in the top-left corner or overlap, the layout was never applied to the parent. Either pass the parent in the constructor (`QVBoxLayout(parent)`) or call `parent.setLayout(layout)`. A layout with no parent widget does nothing." }
      ]
    },
    {
      id: "signals-slots",
      title: "Signals & slots: the core Qt mechanism",
      level: "core",
      body: [
        { type: "p", text: "**Signals & slots** are Qt's type-safe observer pattern and the beating heart of every Qt app. An object **emits a signal** when something happens (a button was clicked, text changed); you **connect** that signal to a **slot** (any callable) that reacts. It decouples the emitter from the handler." },
        { type: "code", lang: "python", code: "button.clicked.connect(self.on_save)          # connect built-in signal -> method\nline.textChanged.connect(self.on_text)        # signal can pass an argument\nslider.valueChanged.connect(label.setNum)     # slot is any callable, incl. a Qt slot\ncombo.currentTextChanged.connect(print)        # connect to a plain function\n\n# a signal can have MANY connections; all are called, in connection order\nbutton.clicked.connect(self.log_click)\nbutton.clicked.connect(self.do_save)" },
        { type: "heading", text: "Defining your own signals" },
        { type: "p", text: "Custom signals must be **class attributes** on a `QObject` subclass, declared with `Signal(types...)`. Emit them with `.emit(...)`. This is how a worker tells the GUI \"I'm done, here's the result\" — crucial for threading." },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QObject, Signal, Slot\n\nclass Worker(QObject):\n    progress = Signal(int)                    # signal carrying an int\n    finished = Signal(str)                    # signal carrying a str\n    error    = Signal(str)\n\n    @Slot()                                   # optional but recommended decorator\n    def run(self):\n        for i in range(101):\n            self.progress.emit(i)             # notify listeners\n        self.finished.emit(\"done\")\n\nw = Worker()\nw.progress.connect(lambda v: print(\"progress\", v))\nw.finished.connect(lambda msg: print(msg))\nw.run()" },
        { type: "list", items: [
          "**`@Slot()`** decorates a method as a slot. It's optional for plain Python callables but improves performance and is **required** for cross-thread queued connections and QML-exposed methods. Annotate the arg types: `@Slot(int)`.",
          "**Overloaded signals**: pass the type to disambiguate — e.g. `combo.currentIndexChanged[int]` vs `[str]` (though most Qt6 signals now have a single signature).",
          "**Disconnect** with `signal.disconnect(slot)` or `signal.disconnect()` (all). Connections are also dropped automatically when either object is destroyed.",
          "Signals return **nothing** — they are fire-and-forget notifications, not function calls with a return value."
        ] },
        { type: "callout", variant: "gotcha", text: "**Lambda in a loop captures the variable, not its value.** `for i in range(3): btn[i].clicked.connect(lambda: use(i))` fires with `i == 2` every time. Bind it: `lambda checked=False, i=i: use(i)`. Note the leading `checked` param — `clicked` emits a `bool`, which would otherwise land in your first argument." },
        { type: "callout", variant: "warn", text: "A lambda or `functools.partial` connected to a signal keeps a reference to whatever it captures (often `self`), which can prevent garbage collection or, if the captured object is deleted, crash on emit. For long-lived connections prefer a real bound method." }
      ]
    },
    {
      id: "mainwindow",
      title: "QMainWindow: menus, toolbars, status bar, docks & QAction",
      level: "core",
      body: [
        { type: "p", text: "`QMainWindow` gives you the standard app chrome for free: a **menu bar**, **tool bars**, a **status bar**, dockable panels, and one **central widget** in the middle. You set your main content with `setCentralWidget(...)`." },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import QMainWindow, QTextEdit, QToolBar, QStatusBar\nfrom PySide6.QtGui import QAction, QKeySequence, QIcon\nfrom PySide6.QtCore import Qt\n\nclass Editor(QMainWindow):\n    def __init__(self):\n        super().__init__()\n        self.setCentralWidget(QTextEdit())\n\n        # --- QAction: a shared command (menu + toolbar + shortcut in one object) ---\n        save = QAction(QIcon.fromTheme(\"document-save\"), \"&Save\", self)\n        save.setShortcut(QKeySequence.StandardKey.Save)   # Ctrl+S, platform-correct\n        save.setStatusTip(\"Save the document\")\n        save.triggered.connect(self.on_save)\n\n        quit_ = QAction(\"&Quit\", self)\n        quit_.setShortcut(\"Ctrl+Q\")\n        quit_.triggered.connect(self.close)\n\n        # --- menu bar ---\n        file_menu = self.menuBar().addMenu(\"&File\")\n        file_menu.addAction(save)\n        file_menu.addSeparator()\n        file_menu.addAction(quit_)\n\n        # --- tool bar (reuses the SAME QAction objects) ---\n        toolbar = QToolBar(\"Main\")\n        toolbar.addAction(save)\n        self.addToolBar(toolbar)\n\n        # --- status bar ---\n        self.setStatusBar(QStatusBar())\n        self.statusBar().showMessage(\"Ready\", 3000)   # transient message, 3s\n\n    def on_save(self):\n        self.statusBar().showMessage(\"Saved\", 2000)" },
        { type: "p", text: "**`QAction`** is the key abstraction: one action object represents a command (Save, Undo, Bold) and can appear simultaneously in a menu, a toolbar, and a context menu, all sharing one enabled-state, icon, shortcut and `triggered` signal. Toggle-style actions use `setCheckable(True)` and emit `toggled(bool)`." },
        { type: "heading", text: "Dock widgets" },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import QDockWidget, QListWidget\nfrom PySide6.QtCore import Qt\n\ndock = QDockWidget(\"Files\", self)\ndock.setWidget(QListWidget())\ndock.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea | Qt.DockWidgetArea.RightDockWidgetArea)\nself.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, dock)   # user can drag/float it" },
        { type: "callout", variant: "note", text: "In Qt6, **`QAction` and `QKeySequence` live in `QtGui`**, not `QtWidgets` (they moved from `QtWidgets` in Qt5). A wrong import here is a common porting error." },
        { type: "callout", variant: "tip", text: "Use `QKeySequence.StandardKey.*` (Save, Copy, Undo, Find...) instead of hard-coding `\"Ctrl+S\"` — Qt maps it to the correct platform shortcut (e.g. Cmd on macOS)." }
      ]
    },
    {
      id: "dialogs",
      title: "Dialogs: built-ins and custom",
      level: "core",
      body: [
        { type: "p", text: "Qt ships ready-made dialogs for the common cases, all invoked with static convenience methods that block until the user responds and return the choice." },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import QMessageBox, QFileDialog, QInputDialog, QColorDialog\n\n# message box: returns which button was pressed\nresult = QMessageBox.question(self, \"Confirm\", \"Delete this file?\",\n    QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)\nif result == QMessageBox.StandardButton.Yes:\n    ...\nQMessageBox.warning(self, \"Oops\", \"Something went wrong\")\nQMessageBox.information(self, \"FYI\", \"Done\")\n\n# file dialogs: return (path, selected_filter); path is \"\" if cancelled\npath, _ = QFileDialog.getOpenFileName(self, \"Open\", \"\", \"Text files (*.txt);;All (*)\")\npath, _ = QFileDialog.getSaveFileName(self, \"Save As\")\nfolder  = QFileDialog.getExistingDirectory(self, \"Choose folder\")\n\n# simple input prompts\ntext, ok = QInputDialog.getText(self, \"Name\", \"Enter your name:\")\nnum,  ok = QInputDialog.getInt(self, \"Age\", \"Enter age:\", 18, 0, 120)\ncolor    = QColorDialog.getColor()                # returns a QColor" },
        { type: "heading", text: "Custom dialogs: QDialog" },
        { type: "p", text: "For anything bespoke, subclass **`QDialog`**. Show it **modally** with `exec()` (blocks, returns `Accepted`/`Rejected`) or **modelessly** with `show()` (non-blocking). A `QDialogButtonBox` gives you standard OK/Cancel wiring." },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import (\n    QDialog, QDialogButtonBox, QVBoxLayout, QLineEdit, QFormLayout,\n)\n\nclass NameDialog(QDialog):\n    def __init__(self, parent=None):\n        super().__init__(parent)\n        self.setWindowTitle(\"Enter name\")\n        self.name = QLineEdit()\n\n        form = QFormLayout()\n        form.addRow(\"Name:\", self.name)\n\n        buttons = QDialogButtonBox(\n            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)\n        buttons.accepted.connect(self.accept)   # -> exec() returns Accepted\n        buttons.rejected.connect(self.reject)   # -> exec() returns Rejected\n\n        layout = QVBoxLayout(self)\n        layout.addLayout(form)\n        layout.addWidget(buttons)\n\n# use it modally:\ndlg = NameDialog(self)\nif dlg.exec() == QDialog.DialogCode.Accepted:\n    print(\"name is\", dlg.name.text())" },
        { type: "callout", variant: "tip", text: "**Modal (`exec()`)** blocks input to the rest of the app until dismissed — right for \"you must answer this now\" prompts. **Modeless (`show()`)** lets the user keep working (a find/replace panel). A modeless dialog needs a kept reference or it is garbage-collected and vanishes." }
      ]
    },
    {
      id: "model-view",
      title: "Model/View architecture",
      level: "core",
      body: [
        { type: "p", text: "The item widgets (`QTableWidget` etc.) store data *inside* the view — fine for small sets, wasteful for large or shared data. The **model/view** framework separates the **data (model)** from its **presentation (view)**, so one dataset can feed multiple views and huge tables render lazily. This is the professional way to display collections." },
        { type: "list", items: [
          "**Views:** `QListView`, `QTableView`, `QTreeView` — render whatever model you plug in.",
          "**Models:** `QStandardItemModel` (a ready general-purpose store) or a **custom `QAbstractTableModel`/`QAbstractListModel`** wrapping your own Python objects.",
          "**Proxy models:** `QSortFilterProxyModel` sits between model and view to sort and filter without touching the source data.",
          "**Delegates:** `QStyledItemDelegate` customize how individual cells are painted or edited."
        ] },
        { type: "heading", text: "Quick start: QStandardItemModel" },
        { type: "code", lang: "python", code: "from PySide6.QtGui import QStandardItemModel, QStandardItem\nfrom PySide6.QtWidgets import QTableView\n\nmodel = QStandardItemModel(0, 2)\nmodel.setHorizontalHeaderLabels([\"Name\", \"Age\"])\nfor name, age in [(\"Alice\", 30), (\"Bob\", 25)]:\n    model.appendRow([QStandardItem(name), QStandardItem(str(age))])\n\nview = QTableView()\nview.setModel(model)" },
        { type: "heading", text: "Custom QAbstractTableModel" },
        { type: "p", text: "For real apps, wrap your own data. Implement the four essential methods — `rowCount`, `columnCount`, `data`, and `headerData`. `data()` is called with a **role** (`DisplayRole` for text, `TextAlignmentRole`, `BackgroundRole`, ...)." },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QAbstractTableModel, Qt, QModelIndex\n\nclass PersonModel(QAbstractTableModel):\n    HEADERS = [\"Name\", \"Age\"]\n\n    def __init__(self, people):\n        super().__init__()\n        self._rows = people           # list of (name, age) tuples\n\n    def rowCount(self, parent=QModelIndex()):\n        return len(self._rows)\n\n    def columnCount(self, parent=QModelIndex()):\n        return len(self.HEADERS)\n\n    def data(self, index, role=Qt.ItemDataRole.DisplayRole):\n        if not index.isValid():\n            return None\n        if role == Qt.ItemDataRole.DisplayRole:\n            return str(self._rows[index.row()][index.column()])\n        if role == Qt.ItemDataRole.TextAlignmentRole and index.column() == 1:\n            return Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter\n        return None\n\n    def headerData(self, section, orientation, role=Qt.ItemDataRole.DisplayRole):\n        if role == Qt.ItemDataRole.DisplayRole and orientation == Qt.Orientation.Horizontal:\n            return self.HEADERS[section]\n        return None\n\n    # to mutate: wrap changes in beginInsertRows/endInsertRows or emit dataChanged\n    def add(self, person):\n        self.beginInsertRows(QModelIndex(), len(self._rows), len(self._rows))\n        self._rows.append(person)\n        self.endInsertRows()" },
        { type: "heading", text: "Sorting & filtering with a proxy" },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QSortFilterProxyModel, Qt\n\nproxy = QSortFilterProxyModel()\nproxy.setSourceModel(PersonModel(people))\nproxy.setFilterCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)\nproxy.setFilterKeyColumn(0)                     # filter on the Name column\n\nview.setModel(proxy)                            # view talks to the proxy, not the source\nview.setSortingEnabled(True)                    # click headers to sort\n\n# live search: pipe a QLineEdit into the proxy filter\nsearch.textChanged.connect(proxy.setFilterFixedString)\n\n# read the selected source row through the selection model\nsel = view.selectionModel()\nsel.currentChanged.connect(lambda cur, prev: print(proxy.mapToSource(cur).row()))" },
        { type: "callout", variant: "gotcha", text: "When a view uses a proxy, a view index is a *proxy* index. To get back to your data you must `proxy.mapToSource(index)` before indexing the source model. Forgetting this returns the wrong row after sorting/filtering." },
        { type: "callout", variant: "warn", text: "Never mutate the model's backing list directly and expect the view to notice. Wrap insertions/removals in `beginInsertRows`/`endInsertRows` (and `beginRemoveRows`/`endRemoveRows`), or emit `dataChanged(topLeft, bottomRight)` for edits — otherwise the view and model desync and you get stale rows or crashes." }
      ]
    },
    {
      id: "designer",
      title: "Qt Designer & .ui files",
      level: "core",
      body: [
        { type: "p", text: "**Qt Designer** is a drag-and-drop UI editor that saves an XML **`.ui`** file. You keep visual layout out of your Python and wire only behavior. Two ways to consume a `.ui`:" },
        { type: "code", lang: "bash", code: "pyside6-designer            # launch the visual editor, save form.ui\n\n# OPTION A (recommended): compile .ui to a Python class, ahead of time\npyside6-uic form.ui -o ui_form.py" },
        { type: "code", lang: "python", code: "# Option A: use the generated class via multiple inheritance / composition\nfrom PySide6.QtWidgets import QMainWindow\nfrom ui_form import Ui_MainWindow      # generated by pyside6-uic\n\nclass MainWindow(QMainWindow):\n    def __init__(self):\n        super().__init__()\n        self.ui = Ui_MainWindow()\n        self.ui.setupUi(self)          # builds all the widgets defined in Designer\n        self.ui.saveButton.clicked.connect(self.on_save)   # access by objectName\n\n    def on_save(self):\n        print(self.ui.nameEdit.text())" },
        { type: "code", lang: "python", code: "# Option B: load the .ui at runtime with QUiLoader (no codegen step)\nfrom PySide6.QtUiTools import QUiLoader\nfrom PySide6.QtCore import QFile\n\nloader = QUiLoader()\nfile = QFile(\"form.ui\")\nfile.open(QFile.OpenModeFlag.ReadOnly)\nwindow = loader.load(file)             # returns a live widget tree\nfile.close()\nwindow.show()" },
        { type: "heading", text: "Resources: .qrc and pyside6-rcc" },
        { type: "p", text: "Bundle icons/images/QSS into the binary via a **`.qrc`** resource file, compiled with `pyside6-rcc`. Importing the generated module registers the resources under `:/` paths." },
        { type: "code", lang: "bash", code: "pyside6-rcc resources.qrc -o rc_resources.py" },
        { type: "code", lang: "python", code: "import rc_resources                    # side-effect: registers the resources\nicon = QIcon(\":/icons/save.png\")       # :/ prefix = a compiled resource path" },
        { type: "callout", variant: "tip", text: "Prefer **Option A (`pyside6-uic` codegen)**: you get autocomplete on `self.ui.*`, catch missing widgets at import time, and no runtime XML parsing. Re-run `pyside6-uic` (or wire it into your build) whenever the `.ui` changes — never hand-edit the generated `ui_*.py`." }
      ]
    },
    {
      id: "styling",
      title: "Styling with Qt Style Sheets (QSS)",
      level: "core",
      body: [
        { type: "p", text: "**QSS** is Qt's CSS-like styling language. It looks like web CSS but targets Qt widget classes and properties. Apply it per-widget or globally on the `QApplication`. Combine with `setObjectName` for `#id` selectors and dynamic properties for state-based styling." },
        { type: "code", lang: "python", code: "app.setStyleSheet(\"\"\"\n    QPushButton { background: #41cd52; color: white; border-radius: 6px; padding: 6px 12px; }\n    QPushButton:hover  { background: #35b344; }\n    QPushButton:pressed { background: #2c9a3a; }\n    QPushButton:disabled { background: #cccccc; }\n    QPushButton#primary { font-weight: bold; }      /* #objectName selector */\n    QLineEdit { border: 1px solid #888; padding: 4px; }\n\"\"\")\n\nsave = QPushButton(\"Save\")\nsave.setObjectName(\"primary\")            # matches QPushButton#primary" },
        { type: "code", lang: "css", code: "/* selectors work like CSS: class, id, descendant, pseudo-states */\nQTableView { gridline-color: #ddd; alternate-background-color: #f7f7f7; }\nQTableView::item:selected { background: #41cd52; }\nQGroupBox { border: 1px solid gray; border-radius: 4px; margin-top: 8px; }\nQGroupBox::title { subcontrol-origin: margin; left: 8px; }" },
        { type: "heading", text: "Dark mode & palettes" },
        { type: "p", text: "For color theming beyond stylesheets, use **`QPalette`** — it feeds Qt's native styling and works even where QSS doesn't reach. Qt6 also respects the OS dark/light preference via the `Fusion` style." },
        { type: "code", lang: "python", code: "from PySide6.QtGui import QPalette, QColor\nfrom PySide6.QtCore import Qt\n\napp.setStyle(\"Fusion\")                   # consistent, themeable style across platforms\n\npalette = QPalette()\npalette.setColor(QPalette.ColorRole.Window, QColor(\"#2b2b2b\"))\npalette.setColor(QPalette.ColorRole.WindowText, Qt.GlobalColor.white)\npalette.setColor(QPalette.ColorRole.Base, QColor(\"#3c3c3c\"))\napp.setPalette(palette)" },
        { type: "callout", variant: "gotcha", text: "QSS uses a specificity model like CSS but it is **not** identical, and mixing QSS with `QPalette` can surprise you (a stylesheet on a widget can override palette colors for that widget and its children). Setting *any* stylesheet on some widgets switches them to a non-native rendering path — test on each target OS." },
        { type: "callout", variant: "tip", text: "Toggle styles by state with **dynamic properties**: `w.setProperty(\"error\", True)` then a selector `QLineEdit[error=\"true\"] { border: 1px solid red; }`. After changing a property, call `w.style().unpolish(w); w.style().polish(w)` to force a restyle." }
      ]
    },
    {
      id: "threading",
      title: "Threading: keep the GUI responsive",
      level: "core",
      body: [
        { type: "p", text: "Qt has one **GUI thread** that runs the event loop. Any long operation (network, file crunching, computation) on that thread **freezes the UI**. The iron rule:" },
        { type: "callout", variant: "warn", text: "**Never touch a widget from any thread but the GUI thread.** Do work in a worker thread, then send results back to the GUI thread via a **signal** (queued connections marshal the call safely). Calling `widget.setText(...)` from a worker thread is undefined behavior and will eventually crash." },
        { type: "heading", text: "Pattern 1: worker QObject + moveToThread" },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QObject, QThread, Signal, Slot\n\nclass Worker(QObject):\n    progress = Signal(int)\n    finished = Signal(str)\n\n    @Slot()\n    def run(self):\n        import time\n        for i in range(1, 101):\n            time.sleep(0.02)            # pretend work — safe, we're off the GUI thread\n            self.progress.emit(i)       # signal crosses back to GUI thread safely\n        self.finished.emit(\"complete\")\n\nclass Window(QMainWindow):\n    def start(self):\n        self.thread = QThread()                 # keep a reference or it's GC'd mid-run!\n        self.worker = Worker()\n        self.worker.moveToThread(self.thread)   # worker now lives in the new thread\n\n        self.thread.started.connect(self.worker.run)\n        self.worker.progress.connect(self.progress_bar.setValue)   # safe: queued\n        self.worker.finished.connect(self.on_done)\n        self.worker.finished.connect(self.thread.quit)\n        self.worker.finished.connect(self.worker.deleteLater)\n        self.thread.finished.connect(self.thread.deleteLater)\n\n        self.thread.start()" },
        { type: "heading", text: "Pattern 2: QThreadPool + QRunnable" },
        { type: "p", text: "For fire-and-forget tasks, `QRunnable` in the global `QThreadPool` is lighter than a full `QThread`. Emit results via a small `QObject` signal holder since `QRunnable` isn't a `QObject`." },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QRunnable, QThreadPool, QObject, Signal, Slot\n\nclass Signals(QObject):\n    result = Signal(object)\n\nclass Task(QRunnable):\n    def __init__(self, fn):\n        super().__init__()\n        self.fn = fn\n        self.signals = Signals()\n\n    @Slot()\n    def run(self):\n        self.signals.result.emit(self.fn())      # heavy work, then signal back\n\ntask = Task(lambda: sum(range(10_000_000)))\ntask.signals.result.connect(lambda r: label.setText(str(r)))\nQThreadPool.globalInstance().start(task)" },
        { type: "heading", text: "QTimer: deferred & periodic work on the GUI thread" },
        { type: "code", lang: "python", code: "from PySide6.QtCore import QTimer\n\nQTimer.singleShot(2000, lambda: label.setText(\"2s later\"))   # one-shot, non-blocking\n\ntimer = QTimer(self)                 # periodic; keep a reference\ntimer.timeout.connect(self.tick)\ntimer.start(1000)                    # every 1000 ms, on the GUI thread" },
        { type: "callout", variant: "gotcha", text: "Do **not** call `time.sleep()` or run a blocking loop on the GUI thread to 'wait' — it freezes the UI and the OS may show a beachball/'not responding'. Use `QTimer` for delays and a worker thread for long work. Never use Python's `threading.Thread` to update widgets either — the same GUI-thread rule applies." }
      ]
    },
    {
      id: "qml",
      title: "Qt Quick / QML (the declarative alternative)",
      level: "deep",
      body: [
        { type: "p", text: "**Qt Quick** is Qt's other UI stack. You describe the interface declaratively in **QML** (a JSON-like tree with JavaScript expressions and property bindings), and it renders on the GPU with fluid animations. Python holds the business logic; QML holds the presentation." },
        { type: "code", lang: "text", code: "// main.qml\nimport QtQuick\nimport QtQuick.Controls\n\nApplicationWindow {\n    visible: true; width: 300; height: 160; title: \"QML\"\n    Column {\n        anchors.centerIn: parent; spacing: 10\n        Label { id: out; text: \"count: 0\" }\n        Button {\n            text: \"increment\"\n            onClicked: out.text = \"count: \" + (backend.bump())   // call into Python\n        }\n    }\n}" },
        { type: "code", lang: "python", code: "from PySide6.QtQml import QmlElement\nfrom PySide6.QtGui import QGuiApplication\nfrom PySide6.QtQml import QQmlApplicationEngine\nfrom PySide6.QtCore import QObject, Slot\nimport sys\n\nclass Backend(QObject):\n    def __init__(self): super().__init__(); self._n = 0\n    @Slot(result=int)\n    def bump(self):\n        self._n += 1\n        return self._n\n\napp = QGuiApplication(sys.argv)\nengine = QQmlApplicationEngine()\nengine.rootContext().setContextProperty(\"backend\", Backend())   # expose to QML\nengine.load(\"main.qml\")\nsys.exit(app.exec())" },
        { type: "list", items: [
          "**Prefer QML when:** the UI is touch-first, mobile/embedded, highly animated, or heavily custom-designed (games, kiosks, media apps).",
          "**Prefer Widgets when:** you need native desktop chrome, dense data tables, standard dialogs, and rapid CRUD tooling.",
          "QML uses `QGuiApplication` + `QQmlApplicationEngine` (not `QApplication`). Expose Python objects with `setContextProperty` or the `@QmlElement` registration decorator."
        ] },
        { type: "callout", variant: "note", text: "Everything else in this deck (signals/slots, threading, models) still applies under QML — a `QAbstractListModel` feeds a QML `ListView` just as it feeds a `QListView`." }
      ]
    },
    {
      id: "painting",
      title: "Custom painting: paintEvent, QPainter, pixmaps",
      level: "deep",
      body: [
        { type: "p", text: "For custom-drawn widgets (charts, canvases, indicators) override **`paintEvent`** and draw with a **`QPainter`**. Qt calls `paintEvent` whenever the widget needs redrawing; call `self.update()` to request a repaint (never call `paintEvent` yourself)." },
        { type: "code", lang: "python", code: "from PySide6.QtWidgets import QWidget\nfrom PySide6.QtGui import QPainter, QPen, QBrush, QColor\nfrom PySide6.QtCore import Qt, QRect\n\nclass Canvas(QWidget):\n    def paintEvent(self, event):\n        p = QPainter(self)\n        p.setRenderHint(QPainter.RenderHint.Antialiasing)\n        p.setPen(QPen(QColor(\"#333\"), 2))\n        p.setBrush(QBrush(QColor(\"#41cd52\")))\n        p.drawRoundedRect(QRect(10, 10, 120, 60), 8, 8)\n        p.drawText(20, 45, \"Hello paint\")\n        # p ends automatically when it goes out of scope" },
        { type: "heading", text: "Images: QPixmap & QIcon" },
        { type: "code", lang: "python", code: "from PySide6.QtGui import QPixmap, QIcon\nfrom PySide6.QtCore import Qt\n\npix = QPixmap(\"photo.png\").scaled(200, 200, Qt.AspectRatioMode.KeepAspectRatio,\n                                  Qt.TransformationMode.SmoothTransformation)\nlabel.setPixmap(pix)                        # display an image in a QLabel\n\nbutton.setIcon(QIcon(\"save.png\"))           # QIcon holds multiple sizes/states\nwindow.setWindowIcon(QIcon(\":/icons/app.png\"))" },
        { type: "callout", variant: "tip", text: "**qtawesome** gives you Font Awesome / Material icons as `QIcon`s without shipping PNGs: `import qtawesome as qta; btn.setIcon(qta.icon('fa5s.save'))`. For plotting, **pyqtgraph** (fast, real-time) or **matplotlib**'s Qt backend embed straight into a widget." },
        { type: "callout", variant: "gotcha", text: "A `QPainter` is only valid **inside** `paintEvent` (its target is the widget's back buffer). Don't stash a painter and reuse it later, and don't paint outside `paintEvent`. To draw offscreen, paint onto a `QPixmap`/`QImage` instead." }
      ]
    },
    {
      id: "packaging",
      title: "Packaging & distribution",
      level: "core",
      body: [
        { type: "p", text: "Ship a self-contained executable so users don't need Python or PySide installed. Two mainstream routes:" },
        { type: "heading", text: "PyInstaller (most common)" },
        { type: "code", lang: "bash", code: "pip install pyinstaller\npyinstaller --name MyApp --windowed --onefile main.py\n#   --windowed  : no console window (GUI app)\n#   --onefile   : single bundled executable (slower startup than --onedir)\n#   --icon app.ico\n# output lands in dist/MyApp(.exe)" },
        { type: "heading", text: "pyside6-deploy (Nuitka under the hood)" },
        { type: "p", text: "Qt's own tool compiles your app with **Nuitka** (Python-to-C), often producing faster, smaller binaries and handling Qt plugin/QML bundling automatically." },
        { type: "code", lang: "bash", code: "pip install nuitka\npyside6-deploy main.py            # generates pysidedeploy.spec, builds a native binary\n# edit pysidedeploy.spec to include extra modules/QML/resources, then re-run" },
        { type: "list", items: [
          "**Trim the bundle:** PySide6 is large; exclude Qt modules you don't use (PyInstaller `--exclude-module`, or Nuitka's plugin config) to shrink the binary.",
          "**Include resources:** compile assets into a `.qrc` (`pyside6-rcc`) so paths resolve from the frozen binary; or add data files with PyInstaller's `--add-data`.",
          "**Platform-native installers:** wrap the result with Inno Setup / NSIS (Windows), `create-dmg` (macOS), or an AppImage/`.deb` (Linux). Code-sign on macOS/Windows to avoid gatekeeper warnings.",
          "Test the *frozen* build on a clean machine — missing Qt plugins (`platforms/`, image formats) show up only outside your dev environment."
        ] },
        { type: "callout", variant: "gotcha", text: "The classic frozen-app failure is `could not load the Qt platform plugin \"xcb\"/\"windows\"`. It means the Qt `platforms/` plugin folder wasn't bundled next to the executable — PyInstaller usually handles it, but a stripped-down build or manual copy can lose it. `pyside6-deploy` bundles plugins for you." }
      ]
    },
    {
      id: "common-headaches",
      title: "Common headaches & how to handle them",
      level: "core",
      body: [
        { type: "p", text: "The recurring foot-guns that trip up PySide6 developers. Most are memory-model or threading issues — Python's GC meeting Qt's C++ object ownership." },
        { type: "heading", text: "1. Touching a widget from a non-GUI thread" },
        { type: "callout", variant: "warn", text: "Updating any widget from a worker thread is undefined behavior and crashes intermittently (often much later, hard to reproduce). **Fix:** do work in the worker, `emit` a signal with the result, and let the connected GUI-thread slot update the widget. Qt's queued connections marshal it to the right thread automatically." },
        { type: "heading", text: "2. Window/widget disappears immediately (garbage collected)" },
        { type: "callout", variant: "gotcha", text: "If you create a window/dialog/thread/timer in a function and don't keep a Python reference, Python garbage-collects it and it vanishes (or the thread dies mid-run). **Fix:** store it — `self.win = MyWindow()` (an attribute), not a local. This is the #1 'it flashes and closes' bug." },
        { type: "heading", text: "3. exec() vs the old exec_()" },
        { type: "callout", variant: "gotcha", text: "In Python 2 days `exec` was a keyword, so Qt bindings used `exec_()`. On Python 3 / Qt6, the method is **`exec()`** (PySide6 keeps `exec_()` as an alias; PyQt6 removed it). Use `app.exec()` / `dialog.exec()`." },
        { type: "heading", text: "4. PyQt vs PySide signal/slot differences" },
        { type: "callout", variant: "gotcha", text: "Copy-pasting PyQt code fails on `pyqtSignal`/`pyqtSlot`/`pyqtProperty`. In PySide6 they are **`Signal`/`Slot`/`Property`** from `QtCore`. Also `QAction`/`QKeySequence`/`QShortcut` are in **`QtGui`** in Qt6, not `QtWidgets`." },
        { type: "heading", text: "5. Layout not applied / widgets overlap" },
        { type: "callout", variant: "gotcha", text: "Widgets stacking in the corner means the layout never got attached to a parent. **Fix:** `QVBoxLayout(parent)` (constructor form) or `parent.setLayout(layout)`. Also, add widgets to the layout, not the parent directly, and use `addLayout` (not `addWidget`) for nested layouts." },
        { type: "heading", text: "6. Lambda-in-a-loop captures the last value" },
        { type: "callout", variant: "gotcha", text: "`for i in range(n): btn.clicked.connect(lambda: f(i))` always fires with the final `i`. **Fix:** default-argument capture `lambda checked=False, i=i: f(i)`. Remember `clicked` passes a `bool`, so include the `checked` param first." },
        { type: "heading", text: "7. QSS specificity & the native-style trap" },
        { type: "callout", variant: "note", text: "A stylesheet on a widget cascades to its children and can override `QPalette` colors; and styling certain widgets switches them off the native renderer, so they look different per OS. Keep global QSS minimal, test on every target platform, and prefer `QPalette` + `Fusion` style for broad theming." },
        { type: "heading", text: "8. Blocking the event loop" },
        { type: "callout", variant: "warn", text: "`time.sleep()`, a tight `while` loop, or a synchronous network call on the GUI thread freezes the UI ('Not Responding'). **Fix:** `QTimer` for delays/polling, a worker thread/`QThreadPool` for real work, and never busy-wait. If you must process events during a long op (rare), `QApplication.processEvents()` — but that re-enters the loop and invites reentrancy bugs, so prefer threads." },
        { type: "callout", variant: "note", text: "General discipline: keep references to top-level windows/threads/timers, run all UI mutation on the GUI thread, prefer signals over shared state, and test the packaged build on a clean machine before shipping." }
      ]
    }
  ],

  packages: [
    { name: "PySide6", why: "the official LGPL Qt6 bindings — QtWidgets, QtCore, QtGui, QtQml, QtCharts, etc., plus the pyside6-* CLI tools" },
    { name: "shiboken6", why: "the C++/Python binding generator PySide is built on; also used to bind your own C++ libraries to Python" },
    { name: "PyQt6", why: "Riverbank's alternative Qt6 bindings (GPL/commercial) — near-identical API, uses pyqtSignal/pyqtSlot; common in legacy code" },
    { name: "Qt Designer (pyside6-designer)", why: "visual drag-and-drop UI editor producing .ui XML; compile with pyside6-uic" },
    { name: "qtawesome", why: "Font Awesome / Material / Elusive icon fonts exposed as QIcon (qta.icon('fa5s.save')) — no PNG assets needed" },
    { name: "pyqtgraph", why: "fast, real-time plotting and image display widgets built on Qt — far quicker than matplotlib for live data" },
    { name: "matplotlib (Qt backend)", why: "embed publication-quality static plots in a widget via FigureCanvasQTAgg" },
    { name: "QScintilla / QtWebEngine", why: "advanced code-editor component and an embedded Chromium web view for rich content" },
    { name: "PyInstaller", why: "freeze the app into a standalone executable (--windowed --onefile); the most common packaging route" },
    { name: "Nuitka (via pyside6-deploy)", why: "compile Python to C for smaller/faster native binaries; pyside6-deploy drives it and bundles Qt plugins/QML" },
    { name: "pytest-qt", why: "test PySide/PyQt GUIs — qtbot fixture to simulate clicks/keys and wait for signals" },
    { name: "QDarkStyleSheet / qt-material", why: "ready-made dark and Material QSS themes you apply to the QApplication" }
  ],

  gotchas: [
    "**Never update widgets off the GUI thread.** Do work in a worker, `emit` a signal, and let the GUI-thread slot touch the widget. Direct cross-thread widget access crashes intermittently.",
    "**Keep a reference to windows/dialogs/threads/timers.** A local variable gets garbage-collected and the window vanishes or the thread dies mid-run. Store it on `self`.",
    "**`exec()` not `exec_()`** in Qt6/Python3. PySide6 keeps `exec_()` as an alias; PyQt6 dropped it. Use `app.exec()` / `dialog.exec()`.",
    "**PySide uses `Signal`/`Slot`/`Property`** (from `QtCore`); PyQt uses `pyqtSignal`/`pyqtSlot`/`pyqtProperty`. Porting code means renaming these.",
    "**`QAction`, `QKeySequence`, `QShortcut` moved to `QtGui`** in Qt6 (they were in `QtWidgets` in Qt5). Wrong import is a frequent porting error.",
    "**Apply the layout to a parent** — `QVBoxLayout(parent)` or `parent.setLayout(layout)`. A layout with no parent does nothing and widgets pile up in the corner.",
    "**`addWidget` for widgets, `addLayout` for nested layouts.** Mixing them silently misplaces content.",
    "**Lambda-in-a-loop captures the variable, not the value** — bind with `lambda checked=False, i=i: f(i)`. `clicked` also passes a `bool` you must absorb.",
    "**Call `super().__init__()`** first in every QObject/QWidget subclass, or the underlying C++ object is uninitialized and you get cryptic crashes.",
    "**Don't block the event loop** with `time.sleep()` or tight loops on the GUI thread — use `QTimer` for delays and a worker thread for work; the UI freezes otherwise.",
    "**Model edits must be wrapped**: `beginInsertRows`/`endInsertRows`, `beginRemoveRows`/`endRemoveRows`, or emit `dataChanged` — mutating the backing list silently desyncs the view.",
    "**With a proxy model, map indexes**: `proxy.mapToSource(index)` before touching the source model, or you read the wrong row after sort/filter.",
    "**QSS cascades and can override QPalette**; styling some widgets switches off native rendering. Keep global stylesheets minimal and test per OS.",
    "**Frozen-app 'could not load the Qt platform plugin'** means the `platforms/` plugin folder wasn't bundled — use `pyside6-deploy` or verify PyInstaller included Qt plugins.",
    "**One `QApplication` per process**, created before any widget; QML apps use `QGuiApplication` + `QQmlApplicationEngine` instead.",
    "**A `QPainter` is only valid inside `paintEvent`.** Request repaints with `self.update()`; never call `paintEvent` yourself or stash a painter for later."
  ],

  flashcards: [
    { q: "PySide6 vs PyQt6 — the key differences?", a: "Same Qt, near-identical API. **PySide6** = official, **LGPL** (proprietary apps OK), uses `Signal`/`Slot`. **PyQt6** = Riverbank, **GPL or paid**, uses `pyqtSignal`/`pyqtSlot`. Both use `exec()` in Qt6." },
    { q: "What are signals and slots?", a: "Qt's observer pattern. An object **emits a signal** when something happens; you **connect** it to a **slot** (any callable) that reacts. `button.clicked.connect(self.on_click)`. Decouples emitter from handler; one signal can have many connections." },
    { q: "How do you define a custom signal?", a: "As a **class attribute** on a `QObject` subclass: `progress = Signal(int)`. Emit with `self.progress.emit(42)`. Decorate handler methods with `@Slot(int)`. Crucial for sending worker results to the GUI thread." },
    { q: "The one iron rule of Qt threading?", a: "**Never touch a widget from a non-GUI thread.** Do work in a worker, `emit` a signal with the result; the connected GUI-thread slot updates the UI. Qt's queued connections marshal it safely across threads." },
    { q: "Two ways to run a background task in Qt?", a: "**(1) `QObject` worker + `moveToThread(QThread)`** — full control, signals for progress/finished. **(2) `QRunnable` + `QThreadPool`** — lighter, fire-and-forget; emit results via a small QObject signal holder. Keep references to threads." },
    { q: "modal exec() vs modeless show() for dialogs?", a: "`exec()` blocks input to the app until the dialog closes and returns `Accepted`/`Rejected` (use for must-answer prompts). `show()` is non-blocking (use for panels) but you must keep a reference or it's garbage-collected." },
    { q: "What does QMainWindow give you?", a: "Standard app chrome: `menuBar()`, tool bars (`addToolBar`), `statusBar()`, dock widgets (`addDockWidget`), and one `setCentralWidget(...)`. Commands are `QAction`s shared across menu + toolbar + shortcut." },
    { q: "Why use model/view instead of QTableWidget?", a: "Model/view separates data (model) from presentation (view), so one dataset feeds multiple views, renders large data lazily, and supports sorting/filtering via `QSortFilterProxyModel`. Item widgets store data in the view — fine only for small sets." },
    { q: "Four methods to implement in a QAbstractTableModel?", a: "`rowCount`, `columnCount`, `data(index, role)` (returns text for `DisplayRole`, etc.), and `headerData`. Wrap mutations in `beginInsertRows`/`endInsertRows` or emit `dataChanged` so the view updates." },
    { q: "How do you use a .ui file from Qt Designer?", a: "Compile it with `pyside6-uic form.ui -o ui_form.py`, then `self.ui = Ui_MainWindow(); self.ui.setupUi(self)` and access widgets by objectName. Or load at runtime with `QUiLoader`. Codegen is preferred (autocomplete, early errors)." },
    { q: "What is QSS and how do you apply it?", a: "Qt Style Sheets — CSS-like styling of widgets. `app.setStyleSheet(\"QPushButton:hover { ... }\")` globally or per widget. Use `setObjectName` for `#id` selectors and dynamic properties for state-based rules. `QPalette` + `Fusion` for broad theming." },
    { q: "Why does my window flash and immediately close?", a: "You didn't keep a Python reference — it was garbage-collected. Store it: `self.win = MyWindow()` on an attribute, not a local variable. Same for dialogs, threads, and timers." },
    { q: "The lambda-in-a-loop connect bug?", a: "`for i in range(n): b.clicked.connect(lambda: f(i))` fires with the last `i`. Bind via default arg: `lambda checked=False, i=i: f(i)`. The leading `checked` absorbs the `bool` that `clicked` emits." },
    { q: "How do you do custom drawing?", a: "Override `paintEvent(self, event)`, create a `QPainter(self)`, set pen/brush and draw. Request redraws with `self.update()` (never call `paintEvent` directly). A `QPainter` is only valid inside `paintEvent`." },
    { q: "How do you package a PySide6 app?", a: "**PyInstaller** (`pyinstaller --windowed --onefile main.py`) or **`pyside6-deploy`** (Nuitka, compiles to native + bundles Qt plugins/QML). Test the frozen build on a clean machine; watch for missing `platforms/` plugins." },
    { q: "When choose Qt Quick/QML over Widgets?", a: "QML (declarative, GPU-accelerated, animation-first) for touch/mobile/embedded and highly custom fluid UIs; Widgets for native desktop chrome, dense data tables, and standard dialogs. QML uses `QGuiApplication` + `QQmlApplicationEngine`." },
    { q: "What is QTimer for?", a: "GUI-thread scheduling. `QTimer.singleShot(ms, fn)` for a one-shot delay; a `QTimer` with `timeout.connect(...)` + `start(ms)` for periodic work. Use it instead of `time.sleep()`, which would freeze the UI." }
  ],

  cheatsheet: [
    { label: "Install", code: "pip install PySide6" },
    { label: "Minimal app", code: "app = QApplication(sys.argv); w = QWidget(); w.show(); sys.exit(app.exec())" },
    { label: "Connect signal", code: "button.clicked.connect(self.on_click)" },
    { label: "Custom signal", code: "class W(QObject): done = Signal(str)   # emit: self.done.emit('x')" },
    { label: "VBox layout", code: "lay = QVBoxLayout(parent); lay.addWidget(w); lay.addStretch()" },
    { label: "Form layout", code: "form = QFormLayout(); form.addRow('Name:', QLineEdit())" },
    { label: "QAction + shortcut", code: "a = QAction('&Save', self); a.setShortcut(QKeySequence.StandardKey.Save)" },
    { label: "Message box", code: "QMessageBox.question(self, 'Q', 'Sure?', QMessageBox.StandardButton.Yes)" },
    { label: "Open file", code: "path, _ = QFileDialog.getOpenFileName(self, 'Open')" },
    { label: "Modal dialog", code: "if dlg.exec() == QDialog.DialogCode.Accepted: ..." },
    { label: "Table model view", code: "view = QTableView(); view.setModel(proxy)   # proxy wraps source" },
    { label: "Sort/filter proxy", code: "proxy.setSourceModel(m); search.textChanged.connect(proxy.setFilterFixedString)" },
    { label: "Worker thread", code: "w.moveToThread(t); t.started.connect(w.run); t.start()  # keep refs!" },
    { label: "QTimer", code: "QTimer.singleShot(1000, self.later)   # or t.timeout.connect(f); t.start(1000)" },
    { label: "Global QSS", code: "app.setStyleSheet('QPushButton:hover { background: #35b344; }')" },
    { label: "Compile .ui", code: "pyside6-uic form.ui -o ui_form.py" },
    { label: "Compile resources", code: "pyside6-rcc res.qrc -o rc_res.py" },
    { label: "Package (PyInstaller)", code: "pyinstaller --windowed --onefile main.py" },
    { label: "Package (Nuitka)", code: "pyside6-deploy main.py" }
  ]
});
