(window.FRAMEWORKS = window.FRAMEWORKS || []).push({
  id: "qt-cpp",
  name: "Qt (C++)",
  language: "C++",
  group: "Desktop GUI",
  navLabel: "Qt (C++)",
  color: "#41cd52",
  readMinutes: 34,
  tagline: "**Qt 6** in native C++ — the flagship cross-platform GUI toolkit. **Widgets** for classic desktop, **Qt Quick/QML** for fluid & touch, **signals & slots** everywhere, one codebase for desktop, mobile and embedded.",

  sections: [
    {
      id: "overview",
      title: "Overview: what Qt is, editions & licensing",
      level: "core",
      body: [
        { type: "p", text: "**Qt** is a mature, batteries-included C++ application framework: a widget toolkit, an event loop, a declarative UI language (QML), plus cross-platform networking, painting, multimedia, SQL, XML/JSON, threading and more. One C++ codebase compiles to **Windows, macOS, Linux, Android, iOS and embedded/RTOS**. It is by far the most widely used C++ GUI framework." },
        { type: "p", text: "Qt is more than a UI library — it extends C++ with its own **object model** (`QObject`), a **meta-object system** (introspection, properties, signals & slots) generated by a code generator called **moc**, and a large standard library of value types (`QString`, `QList`, `QVariant`...). You will write recognizably 'Qt-flavored' C++, not plain STL C++." },
        { type: "heading", text: "Licensing — the thing to get right before you ship" },
        { type: "table", headers: ["Edition", "License", "What it means"], rows: [
          ["Open Source", "**LGPLv3** (most modules) / GPLv3 (a few tools)", "Free. You may ship a **proprietary** app if you **dynamically link** Qt and let users relink (ship the Qt DLLs/.so, don't statically link without care)."],
          ["Commercial", "Paid per-developer", "Required for **static linking** into a closed app, some add-on modules, and to avoid LGPL obligations. Also gives support + long-term-support branches."],
          ["Marketplace add-ons", "Varies", "Some modules (e.g. Qt for MCUs, safety-certified variants) are commercial-only."]
        ] },
        { type: "callout", variant: "warn", text: "The LGPL 'gotcha' for C++: **static linking** Qt into a proprietary binary triggers relinking/source obligations. Most commercial Qt apps either buy a license or ship Qt as shared libraries. If in doubt, dynamic-link and bundle the Qt runtime — that is LGPL-clean." },
        { type: "heading", text: "Qt 6 vs Qt 5" },
        { type: "list", items: [
          "**Qt 6** (current: **6.11**, mid-2026) is the target for new work. It requires a **C++17** compiler, defaults to **CMake**, modernized many APIs, uses `QList == QVector` (unified), and improved high-DPI and graphics (RHI abstraction over Vulkan/Metal/D3D/OpenGL).",
          "**Qt 5** (final 5.15 LTS) is legacy but still huge in the wild; it used **qmake** by default and `QRegExp`, `QLinkedList`, `QStringRef` etc. that Qt 6 removed.",
          "Porting Qt5→Qt6 is mostly mechanical but not free: dropped classes, `QList`/`QVector` merge, container `count()`/`length()` returning `qsizetype`, and module reshuffles (e.g. `QRegExp`→`QRegularExpression`)."
        ] },
        { type: "heading", text: "The two UI paths — pick one primary per window" },
        { type: "table", headers: ["", "Qt Widgets", "Qt Quick / QML"], rows: [
          ["Style", "Imperative C++ (`new QPushButton`)", "Declarative QML + JS bindings"],
          ["Look", "Native-ish, desktop chrome", "Custom-drawn, GPU-accelerated, animated"],
          ["Best for", "Dense desktop tools, forms, tables, IDEs", "Touch, mobile, embedded, kiosks, fluid custom UIs"],
          ["Renderer", "CPU (raster) / native", "Scene graph on GPU (RHI)"],
          ["App class", "`QApplication`", "`QGuiApplication` + `QQmlApplicationEngine`"]
        ] },
        { type: "callout", variant: "note", text: "This deck is **C++**. The sibling **PySide6** page covers the same Qt from Python — read it for the scripting angle. Here everything is native C++: the build system, `moc`, memory ownership, and value types are the parts that differ most from the Python experience." }
      ]
    },
    {
      id: "setup",
      title: "Install & your first app",
      level: "core",
      body: [
        { type: "p", text: "There are three common ways to get Qt for C++. All give you the same libraries; they differ in tooling and CI-friendliness." },
        { type: "list", items: [
          "**Qt Online Installer** (`qt.io/download`) — the official GUI installer. Pick a Qt version, the modules you need, and a **kit** (compiler + Qt build, e.g. MSVC 2022 64-bit or GCC). Bundles **Qt Creator**, the IDE. Requires a (free) Qt account.",
          "**Qt Creator** — Qt's own IDE: project wizards, an integrated **Qt Designer**, QML live preview, a visual debugger, and profilers. You can also use Qt from VS Code / CLion / Visual Studio via CMake.",
          "**aqtinstall** (`pip install aqtinstall`) — an unofficial, account-free CLI downloader ideal for **CI/Docker**: `aqt install-qt linux desktop 6.11.0 linux_gcc_64`. Or use your OS package manager (`apt install qt6-base-dev`, `brew install qt`, `vcpkg install qtbase`) — fine for Linux, but versions lag."
        ] },
        { type: "p", text: "The smallest possible Qt program — one `QApplication`, one widget, then hand control to the event loop with `app.exec()`. Nothing appears until the event loop runs." },
        { type: "code", lang: "cpp", code: "#include <QApplication>\n#include <QPushButton>\n\nint main(int argc, char *argv[])\n{\n    QApplication app(argc, argv);          // exactly ONE per process; pass argc/argv\n\n    QPushButton button(\"Hello Qt 6\");\n    button.resize(240, 80);\n    button.show();                         // widgets are hidden until show()\n\n    return app.exec();                     // runs the event loop, returns exit code\n}" },
        { type: "p", text: "Real apps subclass a window. In C++ you split the class into a header (with the `Q_OBJECT` macro — see the CMake/moc section) and a source file." },
        { type: "code", lang: "cpp", code: "// mainwindow.h\n#pragma once\n#include <QMainWindow>\n#include <QPushButton>\n\nclass MainWindow : public QMainWindow {\n    Q_OBJECT                               // REQUIRED for signals/slots/properties\npublic:\n    explicit MainWindow(QWidget *parent = nullptr);\nprivate slots:\n    void onClick();\nprivate:\n    QPushButton *m_button;\n};" },
        { type: "code", lang: "cpp", code: "// mainwindow.cpp\n#include \"mainwindow.h\"\n#include <QDebug>\n\nMainWindow::MainWindow(QWidget *parent) : QMainWindow(parent)\n{\n    setWindowTitle(\"My App\");\n    m_button = new QPushButton(\"Click me\", this);   // 'this' = parent (owns it)\n    setCentralWidget(m_button);\n    connect(m_button, &QPushButton::clicked, this, &MainWindow::onClick);\n}\n\nvoid MainWindow::onClick() { qDebug() << \"clicked\"; }" },
        { type: "callout", variant: "gotcha", text: "Construct the `QApplication` **before** any widget. Creating a `QWidget` with no running application aborts with `QWidget: Must construct a QApplication before a QWidget`." }
      ]
    },
    {
      id: "build-cmake",
      title: "Build system: CMake, moc & Q_OBJECT",
      level: "core",
      body: [
        { type: "p", text: "**CMake is the default build system for Qt 6.** (qmake still works and appears in older projects, but is in maintenance mode — new code uses CMake.) Qt ships CMake helper functions like `qt_standard_project_setup()` and `qt_add_executable()` that wire up all the code-generation steps for you." },
        { type: "code", lang: "cmake", code: "cmake_minimum_required(VERSION 3.16)\nproject(MyApp VERSION 1.0 LANGUAGES CXX)\n\nset(CMAKE_CXX_STANDARD 17)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n# Find Qt. List every module you use as a COMPONENT.\nfind_package(Qt6 REQUIRED COMPONENTS Widgets)\n\n# Turns on AUTOMOC / AUTOUIC / AUTORCC for all following targets.\nqt_standard_project_setup()\n\nqt_add_executable(MyApp\n    main.cpp\n    mainwindow.cpp\n    mainwindow.h            # headers with Q_OBJECT go here so AUTOMOC sees them\n    mainwindow.ui           # .ui files are compiled by uic automatically\n)\n\ntarget_link_libraries(MyApp PRIVATE Qt6::Widgets)\n\n# Platform niceties: no console on Windows, .app bundle on macOS\nset_target_properties(MyApp PROPERTIES\n    WIN32_EXECUTABLE ON\n    MACOSX_BUNDLE ON\n)" },
        { type: "code", lang: "bash", code: "# configure + build (point CMake at your Qt with CMAKE_PREFIX_PATH)\ncmake -S . -B build -DCMAKE_PREFIX_PATH=/path/to/Qt/6.11.0/gcc_64\ncmake --build build -j\n./build/MyApp" },
        { type: "heading", text: "What is moc, and why Q_OBJECT?" },
        { type: "p", text: "C++ has no built-in runtime reflection, but Qt's signals/slots, properties, `qobject_cast`, and QML integration all need it. The **Meta-Object Compiler (`moc`)** scans your headers for the **`Q_OBJECT`** macro and generates an extra `moc_*.cpp` file containing the meta-object: the signal/slot dispatch tables, `metaObject()`, property accessors, etc. `CMAKE_AUTOMOC` runs moc for you on every build." },
        { type: "list", items: [
          "Any class that declares **signals, slots, `Q_PROPERTY`, or `Q_INVOKABLE`** — or is a `QObject` you'll `qobject_cast` — **must** have `Q_OBJECT` as the first line of its body and live in a header moc can see.",
          "`signals:`, `slots:` (or `public slots:`), and `emit` are **macros** Qt defines. `signals` expands to nothing meaningful to the compiler — moc reads them.",
          "The infamous **`undefined reference to vtable for MyClass`** linker error almost always means: you added `Q_OBJECT` but moc didn't run (stale build → re-run `cmake`), or the class is defined in a `.cpp` where AUTOMOC can't find it."
        ] },
        { type: "callout", variant: "gotcha", text: "Added `Q_OBJECT`, or created a new class, and got 'undefined reference to vtable' or 'no such signal'? **Re-run CMake configure** (not just build) so AUTOMOC picks up the new/changed header. Define `Q_OBJECT` classes in **headers**, not inside a `.cpp` (or you must `#include \"file.moc\"` at the bottom yourself)." },
        { type: "callout", variant: "note", text: "Other generators, all auto-run by CMake: **`uic`** compiles Qt Designer `.ui` XML into `ui_*.h`; **`rcc`** compiles `.qrc` resource files into the binary; **`qmlcachegen`** pre-compiles QML." }
      ]
    },
    {
      id: "qobject",
      title: "QObject: object trees, ownership & properties",
      level: "core",
      body: [
        { type: "p", text: "**`QObject`** is the base of most Qt classes (all widgets, timers, network objects...). It brings three things: signals/slots, a **property system**, and — crucially for C++ memory management — **parent-child object trees**." },
        { type: "heading", text: "Ownership: parents delete their children" },
        { type: "p", text: "When you give a `QObject` a **parent**, the parent takes ownership: deleting the parent automatically deletes all children, recursively. This is Qt's answer to manual memory management — you `new` widgets with a parent and (almost) never `delete` them yourself." },
        { type: "code", lang: "cpp", code: "auto *window = new QWidget;                 // top-level, no parent -> you own it\nauto *layout = new QVBoxLayout(window);     // parented to window\nauto *label  = new QLabel(\"Hi\", window);    // parented to window\nauto *button = new QPushButton(\"OK\");\nlayout->addWidget(button);                  // addWidget REPARENTS button to window\n\n// When 'window' is deleted, label, button and layout are deleted too.\n// Deleting a child before the parent is fine — it removes itself from the parent.\ndelete window;                              // one delete frees the whole tree" },
        { type: "list", items: [
          "**Widgets added to a layout are reparented** to the layout's widget — you don't need to pass a parent explicitly for those.",
          "For a `QObject` whose lifetime should end 'soon but not now' (e.g. inside a slot handling its own signal), use **`obj->deleteLater()`** — it defers the delete until the event loop is idle, avoiding use-after-free.",
          "Mixing Qt parent-ownership with `std::unique_ptr`/`new`+`delete` on the **same** object causes double-free. Pick one owner per object: if it has a QObject parent, let the parent free it.",
          "Stack-allocate top-level objects in `main` (`QApplication app; MainWindow w;`) but **heap-allocate children** with a parent."
        ] },
        { type: "heading", text: "Object names & finding children" },
        { type: "code", lang: "cpp", code: "button->setObjectName(\"saveButton\");        // used by QSS #id, tests, Designer\nauto *b = window->findChild<QPushButton*>(\"saveButton\");  // lookup by name\nauto all = window->findChildren<QPushButton*>();          // every descendant button" },
        { type: "heading", text: "The property system & Q_PROPERTY" },
        { type: "p", text: "Every `QObject` has dynamic properties (`setProperty`/`property`, used by QSS state styling and animations). You also declare **static, introspectable properties** with the **`Q_PROPERTY`** macro — this is what exposes C++ data to QML, the property editor, and the animation framework." },
        { type: "code", lang: "cpp", code: "class Thermostat : public QObject {\n    Q_OBJECT\n    Q_PROPERTY(double target READ target WRITE setTarget NOTIFY targetChanged)\npublic:\n    double target() const { return m_target; }\n    void setTarget(double t) {\n        if (qFuzzyCompare(m_target, t)) return;   // guard against redundant emits\n        m_target = t;\n        emit targetChanged(t);                    // NOTIFY signal drives bindings\n    }\nsignals:\n    void targetChanged(double t);\nprivate:\n    double m_target = 20.0;\n};\n\n// dynamic property (no macro) — handy for QSS state:\nwidget->setProperty(\"invalid\", true);" },
        { type: "callout", variant: "note", text: "`QObject` is **non-copyable** by design (identity + parent make copying meaningless). Pass QObjects by pointer or reference, never by value. Value-semantic data goes in the *value types* (`QString`, `QColor`...) covered next." }
      ]
    },
    {
      id: "signals-slots",
      title: "Signals & slots: the core mechanism",
      level: "core",
      body: [
        { type: "p", text: "**Signals & slots** are Qt's type-safe observer pattern and the backbone of every Qt app. An object **emits a signal** when something happens; you **`connect`** it to a **slot** (a member function, free function, lambda, or another signal) that runs in response. It decouples sender from receiver." },
        { type: "heading", text: "The modern (Qt5/6) pointer-to-member syntax — use this" },
        { type: "code", lang: "cpp", code: "// connect(sender, &Sender::signal, receiver, &Receiver::slot)\nconnect(button, &QPushButton::clicked, this, &MainWindow::onSave);\n\n// signals can carry arguments; types must match (checked at COMPILE time)\nconnect(lineEdit, &QLineEdit::textChanged, this, &MainWindow::onTextChanged);\n\n// connect a signal straight to another object's setter\nconnect(slider, &QSlider::valueChanged, spinBox, &QSpinBox::setValue);\n\n// lambda slot (great for small handlers); pass a context object for lifetime\nconnect(button, &QPushButton::clicked, this, [this]{ m_count++; refresh(); });\n\n// one signal, many slots — all fire, in connection order\nconnect(button, &QPushButton::clicked, this, &MainWindow::log);\nconnect(button, &QPushButton::clicked, this, &MainWindow::doSave);" },
        { type: "callout", variant: "tip", text: "The pointer-to-member form is **compile-time checked** and supports lambdas. The old **string-based** `connect(button, SIGNAL(clicked()), this, SLOT(onSave()))` matches by string at **runtime** — a typo silently fails with only a console warning, no autocomplete, no implicit type conversions. Use it only when connecting to a signal whose overload you must disambiguate by string. Prefer `qOverload<int>(&QComboBox::currentIndexChanged)` for overloaded signals instead." },
        { type: "heading", text: "Declaring your own signals & slots" },
        { type: "code", lang: "cpp", code: "class Downloader : public QObject {\n    Q_OBJECT\npublic:\n    void start();\nsignals:                                     // signals are only DECLARED (moc defines)\n    void progress(int percent);\n    void finished(const QString &path);\n    void failed(const QString &reason);\npublic slots:                                // slots are normal member functions\n    void cancel();\n};\n\n// emit inside the class:\nvoid Downloader::start() {\n    // ...\n    emit progress(50);                       // 'emit' is a no-op marker macro\n    emit finished(\"/tmp/file.bin\");\n}" },
        { type: "heading", text: "Connection types & threads" },
        { type: "table", headers: ["Type", "Behavior"], rows: [
          ["`Qt::AutoConnection` (default)", "Direct if sender & receiver are in the **same thread**, else Queued. Almost always what you want."],
          ["`Qt::DirectConnection`", "Slot runs **immediately** in the emitting thread (like a function call). Unsafe across threads."],
          ["`Qt::QueuedConnection`", "Slot is queued as an event and runs in the **receiver's** thread on its next event-loop iteration. The cross-thread-safe path; arguments are copied."],
          ["`Qt::BlockingQueuedConnection`", "Queued, but the emitter **blocks** until the slot returns. Deadlocks if sender & receiver share a thread — never do that."],
          ["`Qt::UniqueConnection` (flag)", "OR-in to prevent a duplicate identical connection."]
        ] },
        { type: "callout", variant: "warn", text: "For **queued** connections, any custom argument type must be **copyable and registered** with `qRegisterMetaType<MyType>()` (built-in Qt types are pre-registered). Forget it and you get a runtime warning: `QObject::connect: Cannot queue arguments of type 'MyType'` and the slot silently never fires." },
        { type: "callout", variant: "gotcha", text: "A lambda connected **without** a context object outlives the receiver and can crash on emit (dangling capture). Always pass a QObject context: `connect(src, &Src::sig, contextObj, [&]{...})` — the connection auto-disconnects when the context is destroyed." }
      ]
    },
    {
      id: "value-types",
      title: "Core value types: QString, containers & implicit sharing",
      level: "core",
      body: [
        { type: "p", text: "Alongside `QObject`s, Qt has a family of **value types** with normal copy semantics. They use **implicit sharing (copy-on-write)**: copying is cheap (shares a data pointer + refcount) until one copy is modified, which triggers a deep copy. Pass them by `const &` and don't fear returning them by value." },
        { type: "heading", text: "QString (UTF-16 text)" },
        { type: "code", lang: "cpp", code: "#include <QString>\nusing namespace Qt::Literals::StringLiterals;   // enables the u\"...\"_s literal (Qt 6.4+)\n\nQString a = \"hello\";                       // implicit from const char* (UTF-8 assumed)\nQString b = u\"world\"_s;                     // preferred: builds a QString at compile time\nQString c = QStringLiteral(\"legacy form\");  // older equivalent of _s\n\nQString msg = QString(\"%1 is %2\").arg(name).arg(age);   // positional formatting\nQString n   = QString::number(3.14159, 'f', 2);          // \"3.14\"\nbool ok; int v = QString(\"42\").toInt(&ok);\n\n// interop with std::string (watch encoding!)\nstd::string s = a.toStdString();           // UTF-8 out\nQString back  = QString::fromStdString(s); // UTF-8 in\nQByteArray utf8 = a.toUtf8();              // for files/sockets" },
        { type: "callout", variant: "gotcha", text: "`QString` is **UTF-16** internally; `std::string`/`const char*` are byte strings. Round-tripping through `toStdString()`/`fromStdString()` assumes **UTF-8** — fine for ASCII, but a `char*` in some other encoding (Latin-1, a Windows code page) will mojibake. Use `toUtf8()`/`fromUtf8()` explicitly for I/O and never build a `QString` from a locale-encoded `char*` without saying so." },
        { type: "heading", text: "QVariant — a type-erased any" },
        { type: "code", lang: "cpp", code: "QVariant v = 42;\nint i = v.toInt();\nv = QColor(\"#41cd52\");\nQColor c = v.value<QColor>();               // typed extraction\nif (v.canConvert<QString>()) { /* ... */ }" },
        { type: "heading", text: "Containers" },
        { type: "table", headers: ["Type", "Use for"], rows: [
          ["`QList<T>`", "The default sequence. In Qt 6 **`QVector` is an alias for `QList`** — one contiguous, growable array."],
          ["`QMap<K,V>`", "Sorted associative (red-black tree); ordered iteration by key."],
          ["`QHash<K,V>`", "Unordered hash map; faster lookup, no ordering."],
          ["`QSet<T>`", "Hash-based unique set."],
          ["`QByteArray`", "Raw bytes / binary / non-Unicode text (files, sockets)."],
          ["`QStringList`", "`QList<QString>` with `join`, `filter`, `split` helpers."]
        ] },
        { type: "code", lang: "cpp", code: "QList<int> nums {1, 2, 3};\nnums.append(4);\nnums << 5;                                  // stream-append operator\nfor (int n : std::as_const(nums)) { /* ... */ }   // as_const avoids detach/COW copy\n\nQMap<QString, int> ages { {\"Alice\", 30}, {\"Bob\", 25} };\nages[\"Carol\"] = 40;\nfor (auto it = ages.cbegin(); it != ages.cend(); ++it)\n    qDebug() << it.key() << it.value();\n\nQStringList parts = QString(\"a,b,c\").split(',');\nQString joined = parts.join(\" | \");" },
        { type: "callout", variant: "tip", text: "Wrap a Qt container in **`std::as_const(...)`** (or use `cbegin/cend`) in range-for loops. A non-const range-for can silently **detach** (deep-copy) a shared container, quietly killing the copy-on-write performance win. This replaces the old `qAsConst()` helper." }
      ]
    },
    {
      id: "widgets",
      title: "Qt Widgets: the widget tour",
      level: "core",
      body: [
        { type: "p", text: "Widgets are visible controls; every one is a `QWidget` subclass and can be a top-level window or a child. `QApplication` owns the event loop that dispatches input, timers and paint events to them." },
        { type: "code", lang: "cpp", code: "#include <QtWidgets>   // umbrella header (or include each class)\n\nauto *label  = new QLabel(\"Static or <b>rich</b> text\");   // subset of HTML\nauto *button = new QPushButton(\"Save\");\nauto *edit   = new QLineEdit;   edit->setPlaceholderText(\"search...\");\nedit->setEchoMode(QLineEdit::Password);                    // masked input\nauto *area   = new QTextEdit;                              // multi-line, rich text\nauto *combo  = new QComboBox;   combo->addItems({\"Red\", \"Green\", \"Blue\"});\nauto *check  = new QCheckBox(\"Enabled\");  check->setChecked(true);\nauto *radio  = new QRadioButton(\"Option A\");               // group in a QButtonGroup\nauto *slider = new QSlider(Qt::Horizontal);  slider->setRange(0, 100);\nauto *spin   = new QSpinBox;   spin->setRange(0, 10);  spin->setValue(3);\nauto *bar    = new QProgressBar;  bar->setRange(0, 100);\n\n// every widget has these:\nbutton->setToolTip(\"Save the document\");\nbutton->setEnabled(false);\nbutton->setObjectName(\"saveBtn\");   // for QSS / findChild / tests" },
        { type: "callout", variant: "note", text: "The convenience item widgets — `QListWidget`, `QTableWidget`, `QTreeWidget` — store their data inside the view and are great for **small, static** sets. For large or shared data, use the **model/view** classes (`QListView`/`QTableView`/`QTreeView` + a model), covered later. Don't shove 100k items into a `QTableWidget`." }
      ]
    },
    {
      id: "mainwindow",
      title: "QMainWindow: menus, toolbars, docks & QAction",
      level: "core",
      body: [
        { type: "p", text: "`QMainWindow` provides the standard app chrome: a **menu bar**, **tool bars**, a **status bar**, dockable panels, and one **central widget**. The unifying abstraction is **`QAction`** — one command object that can appear in a menu, a toolbar, and a context menu simultaneously, sharing its icon, shortcut, enabled-state and `triggered` signal." },
        { type: "code", lang: "cpp", code: "#include <QMainWindow>\n#include <QAction>       // in QtGui in Qt6 (moved from QtWidgets)\n#include <QKeySequence>\n#include <QToolBar>\n#include <QTextEdit>\n\nEditor::Editor()\n{\n    setCentralWidget(new QTextEdit(this));\n\n    // one QAction, reused in menu + toolbar\n    auto *save = new QAction(QIcon::fromTheme(\"document-save\"), \"&Save\", this);\n    save->setShortcut(QKeySequence::Save);          // Ctrl+S, platform-correct\n    save->setStatusTip(\"Save the document\");\n    connect(save, &QAction::triggered, this, &Editor::onSave);\n\n    auto *quit = new QAction(\"&Quit\", this);\n    quit->setShortcut(QKeySequence::Quit);\n    connect(quit, &QAction::triggered, this, &QWidget::close);\n\n    QMenu *file = menuBar()->addMenu(\"&File\");\n    file->addAction(save);\n    file->addSeparator();\n    file->addAction(quit);\n\n    QToolBar *tb = addToolBar(\"Main\");\n    tb->addAction(save);                            // SAME action object\n\n    statusBar()->showMessage(\"Ready\", 3000);        // transient, 3s\n}" },
        { type: "list", items: [
          "**Checkable actions**: `save->setCheckable(true)` gives a toggle that emits `toggled(bool)` (for Bold, view toggles...).",
          "**Dock widgets**: `auto *d = new QDockWidget(\"Files\", this); d->setWidget(list); addDockWidget(Qt::LeftDockWidgetArea, d);` — user can drag, float, or close it.",
          "**Context menus**: override `contextMenuEvent`, build a `QMenu`, `exec(event->globalPos())`.",
          "Save/restore window layout with `saveState()`/`restoreState()` and `saveGeometry()`/`restoreGeometry()` (persist via `QSettings`)."
        ] },
        { type: "callout", variant: "gotcha", text: "In Qt 6, **`QAction`, `QKeySequence`, `QShortcut` live in `QtGui`**, not `QtWidgets` (they moved from Qt5). A wrong `#include` here is a very common porting error — `find_package` still needs `Widgets`, but the include path changed." }
      ]
    },
    {
      id: "layouts",
      title: "Layouts: never hard-code coordinates",
      level: "core",
      body: [
        { type: "p", text: "You almost never `setGeometry` fixed pixels. **Layout managers** arrange children, resize with the window, and handle DPI scaling. A widget gets a layout; the layout holds widgets and nested layouts." },
        { type: "table", headers: ["Layout", "Arranges children"], rows: [
          ["`QVBoxLayout`", "Vertically, top to bottom"],
          ["`QHBoxLayout`", "Horizontally, left to right"],
          ["`QGridLayout`", "In a row/column grid; cells can span"],
          ["`QFormLayout`", "Two columns: label + field rows (forms)"],
          ["`QStackedLayout`", "One child visible at a time (tabs without the bar)"]
        ] },
        { type: "code", lang: "cpp", code: "auto *root  = new QWidget;\nauto *outer = new QVBoxLayout(root);        // pass parent -> layout applied now\n\nauto *form = new QFormLayout;\nform->addRow(\"Name:\",  new QLineEdit);      // label + field, two columns\nform->addRow(\"Email:\", new QLineEdit);\nouter->addLayout(form);                     // NEST a layout with addLayout\n\nauto *row = new QHBoxLayout;\nrow->addStretch();                          // elastic spacer eats leftover space\nrow->addWidget(new QPushButton(\"Cancel\"));\nrow->addWidget(new QPushButton(\"OK\"));\nouter->addLayout(row);\n\nauto *grid = new QGridLayout;\ngrid->addWidget(new QLabel(\"A\"), 0, 0);\ngrid->addWidget(new QLabel(\"B\"), 0, 1);\ngrid->addWidget(new QPushButton(\"Wide\"), 1, 0, 1, 2);   // rowSpan=1, colSpan=2\nouter->addLayout(grid);" },
        { type: "list", items: [
          "**`addStretch()`** inserts a stretchable spacer to push/center widgets; **`addSpacing(px)`** adds a fixed gap.",
          "**Stretch factor**: `layout->addWidget(w, /*stretch=*/2)` grows `w` twice as fast as a `stretch=1` sibling.",
          "**`setContentsMargins(l,t,r,b)`** and **`setSpacing(px)`** tune padding around and between items.",
          "**`addWidget`** for widgets, **`addLayout`** for nested layouts — swapping them silently misplaces content.",
          "**Size policy** (`w->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed)`) tells the layout whether a widget may grow/shrink; `setFixedWidth/Height` locks a dimension; `setMinimumSize`/`setMaximumSize` bound it."
        ] },
        { type: "callout", variant: "gotcha", text: "Widgets piling in the top-left corner or overlapping means the layout was never attached to a parent widget. Fix: pass the parent to the constructor (`new QVBoxLayout(parent)`) or call `parent->setLayout(layout)`. A layout with no parent widget does nothing." }
      ]
    },
    {
      id: "dialogs",
      title: "Dialogs: built-in and custom",
      level: "core",
      body: [
        { type: "p", text: "Qt ships ready-made dialogs invoked through static convenience methods that block until the user answers and return the choice." },
        { type: "code", lang: "cpp", code: "#include <QMessageBox>\n#include <QFileDialog>\n#include <QInputDialog>\n\nauto r = QMessageBox::question(this, \"Confirm\", \"Delete this file?\",\n                              QMessageBox::Yes | QMessageBox::No);\nif (r == QMessageBox::Yes) { /* ... */ }\nQMessageBox::warning(this, \"Oops\", \"Something went wrong\");\n\n// file dialogs return an empty QString if cancelled\nQString path = QFileDialog::getOpenFileName(this, \"Open\", QString(),\n                                            \"Text files (*.txt);;All files (*)\");\nQString out  = QFileDialog::getSaveFileName(this, \"Save As\");\nQString dir  = QFileDialog::getExistingDirectory(this, \"Choose folder\");\n\nbool ok;\nQString name = QInputDialog::getText(this, \"Name\", \"Enter your name:\",\n                                     QLineEdit::Normal, QString(), &ok);" },
        { type: "heading", text: "Custom dialogs: QDialog + accept/reject" },
        { type: "p", text: "For anything bespoke, subclass **`QDialog`**. Show it **modally** with `exec()` (blocks, returns `QDialog::Accepted`/`Rejected`) or **modelessly** with `show()` (non-blocking). A `QDialogButtonBox` wires standard OK/Cancel to `accept()`/`reject()`." },
        { type: "code", lang: "cpp", code: "class NameDialog : public QDialog {\n    Q_OBJECT\npublic:\n    explicit NameDialog(QWidget *parent = nullptr) : QDialog(parent) {\n        setWindowTitle(\"Enter name\");\n        m_name = new QLineEdit(this);\n\n        auto *box = new QDialogButtonBox(\n            QDialogButtonBox::Ok | QDialogButtonBox::Cancel, this);\n        connect(box, &QDialogButtonBox::accepted, this, &QDialog::accept);\n        connect(box, &QDialogButtonBox::rejected, this, &QDialog::reject);\n\n        auto *lay = new QVBoxLayout(this);\n        lay->addWidget(m_name);\n        lay->addWidget(box);\n    }\n    QString name() const { return m_name->text(); }\nprivate:\n    QLineEdit *m_name;\n};\n\n// use it modally, on the stack:\nNameDialog dlg(this);\nif (dlg.exec() == QDialog::Accepted)\n    qDebug() << \"name is\" << dlg.name();" },
        { type: "callout", variant: "tip", text: "**Modal `exec()`** blocks the rest of the app (right for 'you must answer now'). **Modeless `show()`** lets the user keep working (a find panel) — but a heap-allocated modeless dialog needs a parent or a kept pointer, or it leaks / vanishes. Modal dialogs are cleanest as **stack objects** in the calling scope." }
      ]
    },
    {
      id: "model-view",
      title: "Model/View architecture",
      level: "core",
      body: [
        { type: "p", text: "Item widgets store data *inside* the view — wasteful for large or shared data. The **model/view** framework separates the **data (model)** from its **presentation (view)**, so one dataset feeds multiple views and huge tables render lazily. This is the professional way to show collections." },
        { type: "list", items: [
          "**Views:** `QListView`, `QTableView`, `QTreeView` — render whatever model you plug in.",
          "**Models:** `QStandardItemModel` (a ready general-purpose store) or a **custom `QAbstractTableModel`/`QAbstractListModel`** over your own data.",
          "**Proxy models:** `QSortFilterProxyModel` sits between model and view for sorting & filtering without touching the source.",
          "**Delegates:** `QStyledItemDelegate` customize how a cell is painted or edited."
        ] },
        { type: "heading", text: "A custom QAbstractTableModel" },
        { type: "p", text: "Implement the four essentials — `rowCount`, `columnCount`, `data`, `headerData`. `data()` is called with a **role** (`Qt::DisplayRole` for text, `Qt::TextAlignmentRole`, `Qt::BackgroundRole`, ...). To mutate, wrap changes in `beginInsertRows`/`endInsertRows` or emit `dataChanged` so views update." },
        { type: "code", lang: "cpp", code: "struct Person { QString name; int age; };\n\nclass PersonModel : public QAbstractTableModel {\n    Q_OBJECT\n    QList<Person> m_rows;\npublic:\n    int rowCount(const QModelIndex & = {}) const override { return m_rows.size(); }\n    int columnCount(const QModelIndex & = {}) const override { return 2; }\n\n    QVariant data(const QModelIndex &idx, int role = Qt::DisplayRole) const override {\n        if (!idx.isValid()) return {};\n        const Person &p = m_rows.at(idx.row());\n        if (role == Qt::DisplayRole)\n            return idx.column() == 0 ? p.name : QVariant(p.age);\n        if (role == Qt::TextAlignmentRole && idx.column() == 1)\n            return int(Qt::AlignRight | Qt::AlignVCenter);\n        return {};\n    }\n\n    QVariant headerData(int s, Qt::Orientation o, int role = Qt::DisplayRole) const override {\n        if (role != Qt::DisplayRole || o != Qt::Horizontal) return {};\n        return s == 0 ? \"Name\" : \"Age\";\n    }\n\n    void add(const Person &p) {\n        beginInsertRows({}, m_rows.size(), m_rows.size());  // tell views: rows coming\n        m_rows.append(p);\n        endInsertRows();\n    }\n};" },
        { type: "code", lang: "cpp", code: "// wire it up with sorting + live filtering via a proxy\nauto *model = new PersonModel(this);\nauto *proxy = new QSortFilterProxyModel(this);\nproxy->setSourceModel(model);\nproxy->setFilterCaseSensitivity(Qt::CaseInsensitive);\nproxy->setFilterKeyColumn(0);                 // filter on Name\n\nauto *view = new QTableView;\nview->setModel(proxy);                        // view talks to the PROXY\nview->setSortingEnabled(true);\nconnect(search, &QLineEdit::textChanged, proxy, &QSortFilterProxyModel::setFilterFixedString);" },
        { type: "callout", variant: "gotcha", text: "With a proxy, a view index is a **proxy** index. Map it back before touching the source: `model->/*data at*/ proxy->mapToSource(index)`. Skip this and you read the wrong row after sorting/filtering." },
        { type: "callout", variant: "warn", text: "Never mutate the backing list directly and expect the view to notice. Wrap insert/remove in `beginInsertRows`/`endInsertRows` (and the Remove pair), or emit `dataChanged(topLeft, bottomRight, {roles})` for edits — otherwise view and model desync and you get stale rows or crashes." }
      ]
    },
    {
      id: "designer",
      title: "Qt Designer, .ui files & uic",
      level: "core",
      body: [
        { type: "p", text: "**Qt Designer** (standalone, or embedded in Qt Creator) is a drag-and-drop editor that saves an XML **`.ui`** file. Keep visual layout out of your C++ and wire only behavior. `uic` compiles the `.ui` into a `ui_*.h` header (AUTOUIC does this when the `.ui` is listed in `qt_add_executable`)." },
        { type: "code", lang: "cpp", code: "// mainwindow.h\n#include <QMainWindow>\nnamespace Ui { class MainWindow; }          // forward-declared generated class\n\nclass MainWindow : public QMainWindow {\n    Q_OBJECT\npublic:\n    explicit MainWindow(QWidget *parent = nullptr);\n    ~MainWindow();\nprivate slots:\n    void on_saveButton_clicked();            // auto-connected by objectName\nprivate:\n    Ui::MainWindow *ui;\n};" },
        { type: "code", lang: "cpp", code: "// mainwindow.cpp\n#include \"mainwindow.h\"\n#include \"ui_mainwindow.h\"                    // generated by uic from mainwindow.ui\n\nMainWindow::MainWindow(QWidget *parent)\n    : QMainWindow(parent), ui(new Ui::MainWindow) {\n    ui->setupUi(this);                       // builds all Designer widgets\n    // access widgets by objectName: ui->nameEdit, ui->saveButton ...\n    connect(ui->saveButton, &QPushButton::clicked, this, &MainWindow::onSave);\n}\nMainWindow::~MainWindow() { delete ui; }" },
        { type: "list", items: [
          "**Auto-connection**: a slot named `on_<objectName>_<signal>()` plus `QMetaObject::connectSlotsByName` (called inside `setupUi`) wires up automatically — convenient but magic; explicit `connect` is clearer and refactor-safe.",
          "Never hand-edit the generated `ui_*.h`; it is regenerated on every build. Edit the `.ui` in Designer instead.",
          "**Promote** a widget in Designer (right-click → Promote to...) to use your custom subclass while still laying it out visually."
        ] },
        { type: "callout", variant: "tip", text: "For simple, dynamic UIs many teams skip Designer and build in code — it's more diffable and refactorable. Designer shines for large forms and for handing layout to non-C++ designers. Both compile to the same widgets." }
      ]
    },
    {
      id: "qml",
      title: "Qt Quick / QML: the declarative path",
      level: "deep",
      body: [
        { type: "p", text: "**Qt Quick** is Qt's GPU-accelerated, declarative UI stack. You describe the interface in **QML** — a tree of elements with **property bindings** and JavaScript expressions — and drive it from C++. Best for touch, mobile, embedded and fluid custom designs." },
        { type: "code", lang: "text", code: "// Main.qml\nimport QtQuick\nimport QtQuick.Controls\nimport QtQuick.Layouts\n\nApplicationWindow {\n    visible: true; width: 320; height: 200; title: \"QML\"\n\n    ColumnLayout {\n        anchors.centerIn: parent          // anchors = relative positioning\n        spacing: 10\n\n        Label { text: \"count: \" + backend.count }   // BINDING: auto-updates\n        Button {\n            text: \"increment\"\n            onClicked: backend.bump()      // call a C++ Q_INVOKABLE / slot\n        }\n        Rectangle {\n            width: 120; height: 40; radius: 8; color: \"#41cd52\"\n            Behavior on opacity { NumberAnimation { duration: 200 } }\n        }\n    }\n}" },
        { type: "heading", text: "Exposing C++ to QML" },
        { type: "p", text: "The modern way is **declarative registration** with `QML_ELEMENT` + `qt_add_qml_module`. A `Q_PROPERTY` with a `NOTIFY` signal becomes a bindable QML property; `Q_INVOKABLE` methods and slots are callable from QML." },
        { type: "code", lang: "cpp", code: "// backend.h\n#include <QObject>\n#include <QtQml/qqmlregistrations.h>\n\nclass Backend : public QObject {\n    Q_OBJECT\n    QML_ELEMENT                                   // register this type for QML\n    Q_PROPERTY(int count READ count NOTIFY countChanged)\npublic:\n    int count() const { return m_count; }\n    Q_INVOKABLE void bump() { m_count++; emit countChanged(); }  // callable from QML\nsignals:\n    void countChanged();\nprivate:\n    int m_count = 0;\n};" },
        { type: "code", lang: "cpp", code: "// main.cpp\n#include <QGuiApplication>\n#include <QQmlApplicationEngine>\n\nint main(int argc, char *argv[]) {\n    QGuiApplication app(argc, argv);              // NOT QApplication\n    QQmlApplicationEngine engine;\n    engine.loadFromModule(\"MyApp\", \"Main\");       // module URI + Main.qml\n    if (engine.rootObjects().isEmpty()) return -1;\n    return app.exec();\n}" },
        { type: "code", lang: "cmake", code: "# CMakeLists.txt for a QML app\nfind_package(Qt6 REQUIRED COMPONENTS Quick)\nqt_standard_project_setup(REQUIRES 6.5)\nqt_add_executable(MyApp main.cpp)\nqt_add_qml_module(MyApp\n    URI MyApp\n    VERSION 1.0\n    QML_FILES Main.qml\n    SOURCES backend.h backend.cpp        # C++ types with QML_ELEMENT\n)\ntarget_link_libraries(MyApp PRIVATE Qt6::Quick)" },
        { type: "list", items: [
          "**Older/alternative exposure**: `engine.rootContext()->setContextProperty(\"backend\", &obj)` injects a single C++ instance as a global. Simple, but untyped and not tooling-friendly — prefer `QML_ELEMENT` + instantiate in QML, or `QML_SINGLETON` for a shared instance.",
          "Feed lists to a QML `ListView`/`Repeater` with a `QAbstractListModel` exposing named **roles**, exactly like desktop model/view.",
          "Everything else in this deck — signals/slots, threading, `QAbstractItemModel` — applies unchanged under QML."
        ] },
        { type: "callout", variant: "gotcha", text: "A `setContextProperty` object must **outlive** the QML engine, and the engine doesn't take ownership. Passing a stack local or a soon-freed object gives QML a dangling pointer → crashes on the next binding evaluation. Keep exposed objects alive for the app's lifetime." }
      ]
    },
    {
      id: "events",
      title: "The event system: events, filters & custom painting",
      level: "deep",
      body: [
        { type: "p", text: "Beneath signals/slots is the lower-level **event system**. The event loop delivers `QEvent`s (mouse, key, paint, resize, close...) to `QObject::event()`, which dispatches to virtual handlers like `mousePressEvent`, `keyPressEvent`, `paintEvent`. **Signals** are high-level notifications you connect to; **events** are input you override handlers for. Reach for events when a signal doesn't exist for what you need." },
        { type: "code", lang: "cpp", code: "class Canvas : public QWidget {\nprotected:\n    void mousePressEvent(QMouseEvent *e) override {\n        if (e->button() == Qt::LeftButton) m_last = e->position().toPoint();\n    }\n    void keyPressEvent(QKeyEvent *e) override {\n        if (e->key() == Qt::Key_Escape) close();\n        else QWidget::keyPressEvent(e);      // pass unhandled keys upward\n    }\n    void resizeEvent(QResizeEvent *e) override { /* relayout */ QWidget::resizeEvent(e); }\n    void closeEvent(QCloseEvent *e) override {\n        if (hasUnsavedChanges()) e->ignore(); // veto the close\n        else e->accept();\n    }\nprivate:\n    QPoint m_last;\n};" },
        { type: "heading", text: "Event filters — intercept another object's events" },
        { type: "code", lang: "cpp", code: "// watch a widget's events without subclassing it\nlineEdit->installEventFilter(this);\n\nbool MainWindow::eventFilter(QObject *obj, QEvent *ev) {\n    if (obj == lineEdit && ev->type() == QEvent::KeyPress) {\n        auto *k = static_cast<QKeyEvent*>(ev);\n        if (k->key() == Qt::Key_Return) { submit(); return true; }  // consume it\n    }\n    return QMainWindow::eventFilter(obj, ev);    // else default handling\n}" },
        { type: "heading", text: "Custom painting: paintEvent + QPainter" },
        { type: "code", lang: "cpp", code: "void Canvas::paintEvent(QPaintEvent *) {\n    QPainter p(this);                            // target = this widget\n    p.setRenderHint(QPainter::Antialiasing);\n    p.setPen(QPen(QColor(\"#333\"), 2));\n    p.setBrush(QColor(\"#41cd52\"));\n    p.drawRoundedRect(QRect(10, 10, 120, 60), 8, 8);\n    p.drawText(20, 45, \"Hello paint\");\n}   // QPainter ends when it goes out of scope\n\n// request a repaint (NEVER call paintEvent yourself):\nupdate();                                        // schedules a paint event" },
        { type: "callout", variant: "gotcha", text: "A `QPainter` is valid **only inside `paintEvent`** (its target is the widget's back buffer). Don't stash a painter or paint outside `paintEvent`. To draw offscreen, paint onto a `QPixmap`/`QImage`. Trigger redraws with `update()` (coalesced, async) — `repaint()` forces an immediate synchronous paint and can cause flicker/recursion." }
      ]
    },
    {
      id: "threading",
      title: "Threading: keep the GUI responsive",
      level: "core",
      body: [
        { type: "p", text: "Qt has one **GUI thread** running the event loop. Any long operation on it (network, heavy compute, file crunching) **freezes the UI**. Move work off-thread and marshal results back with signals." },
        { type: "callout", variant: "warn", text: "**Never touch a widget (or any GUI object) from a non-GUI thread.** Do work in a worker, `emit` a signal with the result, and let the connected GUI-thread slot update the UI. Qt's queued connections marshal the call to the right thread. Off-thread `widget->setText(...)` is undefined behavior — it may crash much later, hard to reproduce." },
        { type: "heading", text: "Pattern 1: worker QObject + moveToThread (preferred)" },
        { type: "p", text: "The idiomatic pattern is a `QObject` worker **moved to** a `QThread` — **do not subclass `QThread` and override `run()`** for typical work (that runs only `run()` in the new thread, and the QThread object itself lives in the old thread, which trips people up). moveToThread gives the worker its own event loop and clean signal/slot marshalling." },
        { type: "code", lang: "cpp", code: "class Worker : public QObject {\n    Q_OBJECT\npublic slots:\n    void run() {\n        for (int i = 1; i <= 100; ++i) {\n            /* heavy work */\n            emit progress(i);                    // crosses back to GUI thread (queued)\n        }\n        emit finished(\"done\");\n    }\nsignals:\n    void progress(int);\n    void finished(const QString &);\n};\n\nvoid Window::start() {\n    auto *thread = new QThread(this);\n    auto *worker = new Worker;                   // no parent (can't reparent across threads)\n    worker->moveToThread(thread);                // worker now lives in 'thread'\n\n    connect(thread, &QThread::started,  worker, &Worker::run);\n    connect(worker, &Worker::progress,  m_bar,  &QProgressBar::setValue);   // safe\n    connect(worker, &Worker::finished,  thread, &QThread::quit);\n    connect(worker, &Worker::finished,  worker, &QObject::deleteLater);\n    connect(thread, &QThread::finished, thread, &QObject::deleteLater);\n    thread->start();\n}" },
        { type: "heading", text: "Pattern 2: QThreadPool + QRunnable, and QtConcurrent" },
        { type: "code", lang: "cpp", code: "// QRunnable — fire-and-forget task on the global pool\nclass Task : public QRunnable {\n    void run() override { /* heavy work off the GUI thread */ }\n};\nQThreadPool::globalInstance()->start(new Task);   // pool deletes it by default\n\n// QtConcurrent — highest level: run a callable, get a QFuture\n#include <QtConcurrent>\nQFuture<int> f = QtConcurrent::run([]{ return expensiveSum(); });\n\nauto *watcher = new QFutureWatcher<int>(this);\nconnect(watcher, &QFutureWatcher<int>::finished, this,\n        [watcher]{ qDebug() << \"result\" << watcher->result(); });   // on GUI thread\nwatcher->setFuture(f);" },
        { type: "heading", text: "QTimer: scheduling on the GUI thread" },
        { type: "code", lang: "cpp", code: "QTimer::singleShot(2000, this, [this]{ label->setText(\"2s later\"); }); // one-shot\n\nauto *timer = new QTimer(this);           // periodic; parented so it's freed with 'this'\nconnect(timer, &QTimer::timeout, this, &Window::tick);\ntimer->start(1000);                       // every 1000 ms on the GUI thread" },
        { type: "callout", variant: "gotcha", text: "Don't `QThread::sleep()` or spin a blocking loop on the GUI thread to 'wait' — it freezes the UI and the OS shows 'Not Responding'. Use `QTimer` for delays and a worker/`QtConcurrent` for real work. Objects created **inside** a worker's `run()` belong to that thread — construct GUI objects only on the GUI thread." }
      ]
    },
    {
      id: "core-utilities",
      title: "Resources, styling, i18n, settings, files & networking",
      level: "core",
      body: [
        { type: "heading", text: "Resources (.qrc) — bundle assets into the binary" },
        { type: "p", text: "List icons/images/QSS/QML in a **`.qrc`** XML file; `rcc` (AUTORCC / `qt_add_resources`) compiles them into the executable, accessible under the `:/` prefix — no loose files to ship." },
        { type: "code", lang: "xml", code: "<!-- resources.qrc -->\n<RCC>\n  <qresource prefix=\"/\">\n    <file>icons/save.png</file>\n    <file>style/app.qss</file>\n  </qresource>\n</RCC>" },
        { type: "code", lang: "cpp", code: "button->setIcon(QIcon(\":/icons/save.png\"));   // :/ = a compiled resource path\nQFile f(\":/style/app.qss\");" },
        { type: "heading", text: "Styling: Qt Style Sheets (QSS)" },
        { type: "code", lang: "cpp", code: "qApp->setStyleSheet(\n    \"QPushButton { background:#41cd52; color:white; border-radius:6px; padding:6px 12px; }\"\n    \"QPushButton:hover { background:#35b344; }\"\n    \"QPushButton#primary { font-weight:bold; }\");     // #objectName selector\nsaveBtn->setObjectName(\"primary\");\n\n// state via dynamic property + re-polish\nedit->setProperty(\"invalid\", true);   // selector: QLineEdit[invalid=\"true\"]{border:1px solid red;}\nedit->style()->unpolish(edit); edit->style()->polish(edit);   // force restyle" },
        { type: "callout", variant: "note", text: "For broad theming (including OS dark mode), use **`QApplication::setStyle(\"Fusion\")`** + a `QPalette` — it reaches painting QSS doesn't. Mixing QSS and palette can surprise you: a stylesheet on a widget can override palette colors for it and its children, and styling some widgets drops the native renderer. Keep global QSS minimal and test per OS." },
        { type: "heading", text: "Internationalization: tr() + Qt Linguist" },
        { type: "list", items: [
          "Wrap **every user-visible string** in `tr(\"Save\")`. Run **`lupdate`** to extract them into `.ts` files, translate in **Qt Linguist**, then **`lrelease`** compiles `.ts` → binary `.qm`.",
          "Load at startup: `QTranslator t; t.load(\"app_fr.qm\"); app.installTranslator(&t);`.",
          "Use `%1`/`.arg()` (not string concatenation) so translators can reorder; use `tr(\"%n file(s)\", \"\", count)` for plurals."
        ] },
        { type: "heading", text: "Settings, files & networking" },
        { type: "code", lang: "cpp", code: "// QSettings — persistent app config (registry/plist/ini, platform-native)\nQSettings s(\"MyCompany\", \"MyApp\");\ns.setValue(\"geometry\", saveGeometry());\nrestoreGeometry(s.value(\"geometry\").toByteArray());\n\n// QFile / QIODevice + QTextStream\nQFile file(\"data.txt\");\nif (file.open(QIODevice::ReadOnly | QIODevice::Text)) {\n    QTextStream in(&file);\n    QString all = in.readAll();\n}\n\n// QNetworkAccessManager — async HTTP (never blocks the event loop)\nauto *net = new QNetworkAccessManager(this);\nconnect(net, &QNetworkAccessManager::finished, this, [](QNetworkReply *r){\n    qDebug() << r->readAll();\n    r->deleteLater();\n});\nnet->get(QNetworkRequest(QUrl(\"https://example.com/api\")));" },
        { type: "callout", variant: "tip", text: "`QNetworkAccessManager` is **asynchronous by design** — you connect to `finished`/signals, you don't block waiting for the reply. That keeps the GUI responsive without you spawning a thread. `deleteLater()` the `QNetworkReply` when done." }
      ]
    },
    {
      id: "testing",
      title: "Testing with QTest",
      level: "deep",
      body: [
        { type: "p", text: "**Qt Test** is Qt's lightweight unit-test framework. A test is a `QObject` whose **private slots** are test functions; `QTEST_MAIN` generates a `main()`. It integrates with CMake/CTest and can simulate GUI input." },
        { type: "code", lang: "cpp", code: "#include <QtTest>\n#include \"calculator.h\"\n\nclass TestCalculator : public QObject {\n    Q_OBJECT\nprivate slots:\n    void init() { /* runs before each test */ }\n\n    void adds() {\n        Calculator c;\n        QCOMPARE(c.add(2, 3), 5);            // pretty-prints both sides on failure\n        QVERIFY(c.add(2, 3) > 0);            // boolean assertion\n    }\n\n    // data-driven: run the same test over a table of rows\n    void adds_data() {\n        QTest::addColumn<int>(\"a\");\n        QTest::addColumn<int>(\"b\");\n        QTest::addColumn<int>(\"sum\");\n        QTest::newRow(\"positives\") << 2 << 3 << 5;\n        QTest::newRow(\"negatives\") << -1 << -1 << -2;\n    }\n    void addsTable() {\n        QFETCH(int, a); QFETCH(int, b); QFETCH(int, sum);\n        QCOMPARE(Calculator().add(a, b), sum);\n    }\n};\n\nQTEST_MAIN(TestCalculator)\n#include \"test_calculator.moc\"   // needed: Q_OBJECT class lives in a .cpp" },
        { type: "code", lang: "cmake", code: "enable_testing()\nfind_package(Qt6 REQUIRED COMPONENTS Test)\nqt_add_executable(test_calc test_calculator.cpp)\ntarget_link_libraries(test_calc PRIVATE Qt6::Test)\nadd_test(NAME calc COMMAND test_calc)   # run with: ctest" },
        { type: "callout", variant: "note", text: "For GUI tests, `QTest::mouseClick(widget, Qt::LeftButton)` and `QTest::keyClicks(edit, \"hello\")` simulate input; `QSignalSpy spy(obj, &Obj::sig)` records emissions so you can assert `spy.count()`. Because the test class has `Q_OBJECT` inside a `.cpp`, remember the `#include \"file.moc\"` line." }
      ]
    },
    {
      id: "deployment",
      title: "Deployment & packaging",
      level: "core",
      body: [
        { type: "p", text: "A Qt binary needs its Qt shared libraries **and** the right **plugins** (platform integration, image formats, styles) beside it. The `*deployqt` tools scan your executable and copy exactly what it uses." },
        { type: "table", headers: ["Platform", "Tool", "Notes"], rows: [
          ["Windows", "`windeployqt MyApp.exe`", "Copies Qt DLLs + `platforms/qwindows.dll` etc. next to the exe. Bundle the MSVC runtime too."],
          ["macOS", "`macdeployqt MyApp.app -dmg`", "Fills the `.app` bundle's Frameworks dir and can produce a `.dmg`. Then codesign + notarize."],
          ["Linux", "`linuxdeployqt` (community) / AppImage", "No official tool; community `linuxdeployqt`, `cqtdeployer`, or ship an AppImage/Flatpak/`.deb`."]
        ] },
        { type: "code", lang: "cmake", code: "# Cross-platform, CMake-native deployment (Qt 6.3+)\ninstall(TARGETS MyApp BUNDLE DESTINATION . RUNTIME DESTINATION bin)\nqt_generate_deploy_app_script(\n    TARGET MyApp\n    OUTPUT_SCRIPT deploy_script\n    NO_UNSUPPORTED_PLATFORM_ERROR)\ninstall(SCRIPT ${deploy_script})   # `cmake --install build` runs the right *deployqt" },
        { type: "list", items: [
          "**Dynamic (LGPL-clean)** is the default: ship Qt as shared libs + plugins. **Static linking** produces one file but needs a **commercial license** (or careful LGPL relinking provisions) and a statically-built Qt.",
          "**Trim size**: only `find_package`/link the Qt modules you use; QtWebEngine and QtQuick pull in a lot.",
          "**Native installers**: wrap the deployed folder with Inno Setup / NSIS / WiX (Windows), a signed `.dmg`/`.pkg` (macOS), AppImage / `.deb` / Flatpak (Linux). **Code-sign** on macOS & Windows to avoid Gatekeeper/SmartScreen warnings.",
          "**Test the deployed build on a clean machine** — missing plugins only surface outside your dev environment."
        ] },
        { type: "callout", variant: "gotcha", text: "The classic ship-day failure is `This application failed to start because no Qt platform plugin could be initialized` (`xcb` on Linux, `windows` on Windows, `cocoa` on macOS). It means the `platforms/` plugin folder wasn't deployed next to the binary. `windeployqt`/`macdeployqt`/`qt_generate_deploy_app_script` handle it — a hand-copied build usually loses it." }
      ]
    },
    {
      id: "common-headaches",
      title: "Common headaches & how to handle them",
      level: "core",
      body: [
        { type: "p", text: "The recurring foot-guns in C++ Qt. Most are the meta-object system (moc) or the object-ownership model meeting your expectations." },
        { type: "heading", text: "1. undefined reference to vtable / signal not found" },
        { type: "callout", variant: "gotcha", text: "You added `Q_OBJECT`, a signal, or a new QObject subclass and got a link error or `No such signal`. **Fix:** the class must have `Q_OBJECT` as the first line, live in a **header** AUTOMOC scans, and you must **re-run CMake configure** (not just build) so moc regenerates. A `Q_OBJECT` class inside a `.cpp` needs a trailing `#include \"file.moc\"`." },
        { type: "heading", text: "2. Forgetting a parent → leaks or double-free" },
        { type: "callout", variant: "gotcha", text: "A heap `new QWidget` with no parent and no `delete` leaks. Conversely, `delete`ing an object that already has a QObject parent (or that a layout owns) causes a **double-free** when the parent later cleans up. **Fix:** give children a parent and let the parent free them; use `deleteLater()` for objects deleting themselves during signal handling; keep exactly one owner per object." },
        { type: "heading", text: "3. Blocking the event loop" },
        { type: "callout", variant: "warn", text: "`QThread::sleep`, a tight loop, or a synchronous network/file call on the GUI thread freezes the UI ('Not Responding'). **Fix:** `QTimer` for delays, a worker thread / `QtConcurrent` for work, async `QNetworkAccessManager` for I/O. `QApplication::processEvents()` exists but re-enters the loop and invites reentrancy bugs — prefer threads." },
        { type: "heading", text: "4. Touching widgets off the GUI thread" },
        { type: "callout", variant: "warn", text: "Any GUI object access from a worker thread is undefined behavior and crashes intermittently. **Fix:** `emit` a signal from the worker; the connected GUI-thread slot updates the widget. Auto/queued connections marshal it. Also: don't create widgets inside a worker's `run()` — they'd belong to the wrong thread." },
        { type: "heading", text: "5. Signal/slot signature mismatch" },
        { type: "callout", variant: "gotcha", text: "With the pointer-to-member syntax a mismatch is a **compile error** (good). With the old string `SIGNAL()/SLOT()` macros it's a silent **runtime** warning and the slot never fires. **Fix:** use `connect(a, &A::sig, b, &B::slot)`; for overloaded signals disambiguate with `qOverload<int>(&Combo::currentIndexChanged)`. For queued custom types, `qRegisterMetaType<T>()`." },
        { type: "heading", text: "6. QString / encoding pitfalls" },
        { type: "callout", variant: "gotcha", text: "Building a `QString` from a non-UTF-8 `char*`, or `toStdString()` into code that expects a local code page, produces mojibake. **Fix:** be explicit — `QString::fromUtf8`/`toUtf8` for I/O, `u\"...\"_s`/`QStringLiteral` for literals, `%1` + `.arg()` for building strings. `QString` is UTF-16 internally; bytes are `QByteArray`." },
        { type: "heading", text: "7. Layout not applied / widgets overlap" },
        { type: "callout", variant: "gotcha", text: "Widgets piling in the corner = the layout was never parented. **Fix:** `new QVBoxLayout(parent)` or `parent->setLayout(layout)`. Add widgets with `addWidget`, nested layouts with `addLayout`. Don't set fixed geometry and expect a layout to also manage the widget." },
        { type: "heading", text: "8. QML ↔ C++ context lifetime" },
        { type: "callout", variant: "gotcha", text: "An object exposed via `setContextProperty` (or returned to QML) must **outlive the engine** — QML holds a raw pointer and doesn't take ownership. A freed exposed object crashes the next binding evaluation. **Fix:** keep exposed objects alive for the app lifetime, or return QObjects with `QQmlEngine::setObjectOwnership` set correctly; prefer `QML_ELEMENT` registration and instantiate in QML." },
        { type: "callout", variant: "note", text: "General discipline: `Q_OBJECT` + re-run CMake when adding QObjects; one owner per object (usually a parent); all GUI work on the GUI thread; prefer signals to shared state; async I/O; and test the **deployed** build on a clean machine before shipping." }
      ]
    }
  ],

  packages: [
    { name: "Qt Widgets (Qt6::Widgets)", why: "the classic imperative desktop toolkit — QMainWindow, layouts, dialogs, model/view; native-feeling data-dense apps" },
    { name: "Qt Quick / QML (Qt6::Quick, Qt6::Qml)", why: "declarative, GPU-accelerated UI language for touch/mobile/embedded and fluid custom interfaces" },
    { name: "Qt Core (Qt6::Core)", why: "the non-GUI foundation: QObject, signals/slots, QString, containers, QThread, QFile, QSettings, event loop" },
    { name: "Qt Network (Qt6::Network)", why: "async HTTP via QNetworkAccessManager, TCP/UDP sockets, TLS/SSL, WebSockets (with Qt WebSockets)" },
    { name: "Qt Charts (Qt6::Charts)", why: "line/bar/pie/scatter chart widgets and QML chart views for dashboards and data apps" },
    { name: "Qt Test (Qt6::Test)", why: "unit-test framework: QTEST_MAIN, QCOMPARE/QVERIFY, data-driven tests, QSignalSpy, GUI event simulation" },
    { name: "Qt Creator", why: "the official IDE — project wizards, embedded Qt Designer, QML live preview, integrated debugger and profilers" },
    { name: "CMake", why: "the default Qt 6 build system — qt_standard_project_setup, qt_add_executable, qt_add_qml_module, qt_add_resources" },
    { name: "moc / uic / rcc", why: "Qt's code generators (meta-object compiler, .ui compiler, resource compiler), auto-run by CMake AUTOMOC/AUTOUIC/AUTORCC" },
    { name: "Qt Linguist (lupdate/lrelease)", why: "translation workflow — extract tr() strings to .ts, translate, compile to .qm loaded via QTranslator" },
    { name: "windeployqt / macdeployqt / linuxdeployqt", why: "bundle Qt libraries + plugins next to your executable for distribution" },
    { name: "QtConcurrent", why: "high-level parallelism — QtConcurrent::run/map/filter returning QFuture, watched by QFutureWatcher" },
    { name: "Qt WebEngine (Qt6::WebEngineWidgets)", why: "embedded Chromium web view for rendering rich HTML/JS content in-app" },
    { name: "Qt SQL (Qt6::Sql)", why: "database access (SQLite/MySQL/Postgres) with QSqlDatabase, QSqlQuery, and QSqlTableModel for model/view" },
    { name: "PySide6 (sibling)", why: "the official Python bindings for the same Qt — useful for scripting, tooling, or prototyping alongside a C++ core" },
    { name: "vcpkg / Conan / aqtinstall", why: "package managers & CLI installers to fetch Qt for CI and reproducible builds without the GUI installer" }
  ],

  gotchas: [
    "**`Q_OBJECT` + re-run CMake.** Adding signals/slots/properties or a new QObject subclass needs `Q_OBJECT` in the class and a CMake reconfigure so AUTOMOC regenerates — else 'undefined reference to vtable' or 'no such signal'.",
    "**One owner per object.** Give QObjects a parent and let the parent `delete` them; never also `delete` a parented/layout-owned object (double-free). Use `deleteLater()` for self-deletion inside slots.",
    "**Never touch GUI objects off the GUI thread.** Do work in a worker, `emit` a signal, let the GUI-thread slot update the widget. Queued connections marshal it safely.",
    "**Don't block the event loop** with sleeps/tight loops/sync I/O on the GUI thread — use `QTimer`, worker threads/`QtConcurrent`, and async `QNetworkAccessManager`.",
    "**Use the pointer-to-member `connect`** (`&Sender::sig`) — compile-time checked, supports lambdas. The string `SIGNAL()/SLOT()` form fails silently at runtime on a typo.",
    "**Disambiguate overloaded signals** with `qOverload<int>(&QComboBox::currentIndexChanged)`; register custom queued-connection types with `qRegisterMetaType<T>()`.",
    "**Apply layouts to a parent** — `new QVBoxLayout(parent)` or `parent->setLayout(...)`; `addWidget` for widgets, `addLayout` for nested layouts. Otherwise widgets overlap in the corner.",
    "**`QAction`/`QKeySequence`/`QShortcut` are in `QtGui` in Qt6** (moved from QtWidgets in Qt5) — a frequent wrong-include porting error.",
    "**`QString` is UTF-16; bytes are `QByteArray`.** Use `fromUtf8`/`toUtf8` for I/O, `u\"...\"_s`/`QStringLiteral` for literals, `%1`+`.arg()` to build — don't concat with locale-encoded `char*`.",
    "**Wrap Qt containers in `std::as_const`** (or use `cbegin/cend`) in range-for to avoid a silent copy-on-write detach that kills performance.",
    "**Model edits must be wrapped** — `beginInsertRows`/`endInsertRows`, the Remove pair, or emit `dataChanged` — or the view desyncs from the model.",
    "**With a proxy model, `mapToSource(index)`** before touching the source model, or you read the wrong row after sort/filter.",
    "**Prefer worker-QObject + `moveToThread`** over subclassing `QThread::run` for typical work; keep the QThread alive and `deleteLater` worker + thread on finish.",
    "**A `QPainter` is valid only inside `paintEvent`.** Request repaints with `update()`; never call `paintEvent` yourself or stash a painter.",
    "**QML-exposed C++ objects must outlive the engine** (`setContextProperty` takes a raw pointer, no ownership) — a freed object crashes the next binding.",
    "**Deploy the platform plugin.** 'No Qt platform plugin could be initialized' means the `platforms/` folder wasn't bundled — use `windeployqt`/`macdeployqt`/`qt_generate_deploy_app_script`."
  ],

  flashcards: [
    { q: "What does moc do and why is Q_OBJECT needed?", a: "The **Meta-Object Compiler** scans headers for `Q_OBJECT` and generates the meta-object (signal/slot dispatch, properties, `metaObject()`). C++ has no reflection; Qt needs it for signals/slots, `qobject_cast`, properties, and QML. Missing it → 'undefined reference to vtable'." },
    { q: "How does Qt manage widget memory?", a: "**Parent-child object trees.** Giving a `QObject` a parent transfers ownership; deleting the parent recursively deletes children. So you `new` children with a parent and don't `delete` them. Adding a widget to a layout reparents it. Use `deleteLater()` for deferred deletion." },
    { q: "Modern connect syntax vs the old one?", a: "Use `connect(sender, &Sender::sig, receiver, &Receiver::slot)` — **compile-time checked**, supports lambdas. The old `connect(s, SIGNAL(sig()), r, SLOT(slot()))` matches strings at **runtime** and fails silently on a typo. Disambiguate overloads with `qOverload<int>(...)`." },
    { q: "The connection types and when they matter?", a: "`AutoConnection` (default: Direct same-thread, Queued cross-thread), `DirectConnection` (immediate, same thread), `QueuedConnection` (runs in receiver's thread via its event loop — the cross-thread-safe path, args copied), `BlockingQueuedConnection` (emitter blocks; deadlocks if same thread)." },
    { q: "How do you declare a custom signal and slot?", a: "In a `Q_OBJECT` class: under `signals:` declare (moc defines them) e.g. `void progress(int);`; under `public slots:` write a normal member function. Fire with `emit progress(50);`. `emit` is a no-op marker macro." },
    { q: "The default Qt 6 build system and key CMake calls?", a: "**CMake** (qmake is legacy). `find_package(Qt6 REQUIRED COMPONENTS Widgets)`, `qt_standard_project_setup()`, `qt_add_executable(...)`, `target_link_libraries(app PRIVATE Qt6::Widgets)`. AUTOMOC/AUTOUIC/AUTORCC run the generators." },
    { q: "What is implicit sharing (copy-on-write)?", a: "Qt value types (`QString`, `QList`, `QVariant`...) share a data pointer + refcount on copy; a deep copy happens only on modification. Copies are cheap — pass by `const&` and return by value freely. Wrap in `std::as_const` in range-for to avoid accidental detach." },
    { q: "QString vs std::string interop?", a: "`QString` is **UTF-16**; `std::string` is bytes. Convert with `toStdString()`/`fromStdString()` (UTF-8) or `toUtf8()`/`fromUtf8()` for explicit I/O. Build literals with `u\"...\"_s` or `QStringLiteral`; format with `%1`+`.arg()`, not concatenation." },
    { q: "Why model/view over QTableWidget?", a: "It separates data (model) from presentation (view): one dataset feeds multiple views, large data renders lazily, and `QSortFilterProxyModel` adds sort/filter. Item widgets store data in the view — fine only for small, static sets." },
    { q: "Four methods to implement in a QAbstractTableModel?", a: "`rowCount`, `columnCount`, `data(index, role)` (returns the value for `Qt::DisplayRole`, alignment, etc.), and `headerData`. Wrap mutations in `beginInsertRows`/`endInsertRows` (or emit `dataChanged`) so views update." },
    { q: "The iron rule of Qt threading?", a: "**Never touch a GUI object from a non-GUI thread.** Do work in a worker, `emit` a signal with the result; the connected GUI-thread slot updates the UI. Queued connections marshal the call. The preferred pattern is a QObject worker + `moveToThread`." },
    { q: "Three ways to run background work in Qt?", a: "(1) **QObject worker + `moveToThread(QThread)`** — full control, signals for progress/finished. (2) **`QRunnable` + `QThreadPool`** — fire-and-forget. (3) **`QtConcurrent::run`** — returns a `QFuture`, watched by `QFutureWatcher` for the result on the GUI thread." },
    { q: "How do you expose C++ to QML (modern way)?", a: "Add `QML_ELEMENT` (include `<QtQml/qqmlregistrations.h>`) to a `QObject`, expose data via `Q_PROPERTY` with a `NOTIFY` signal and methods via `Q_INVOKABLE`, and register with `qt_add_qml_module`. Older way: `rootContext()->setContextProperty(\"name\", &obj)`." },
    { q: "Widgets app vs QML app entry points?", a: "**Widgets**: `QApplication app; MainWindow w; w.show(); return app.exec();`. **QML**: `QGuiApplication app; QQmlApplicationEngine engine; engine.loadFromModule(\"MyApp\",\"Main\"); return app.exec();` — different app class and no widget tree." },
    { q: "How do you do custom painting?", a: "Override `paintEvent(QPaintEvent*)`, create a `QPainter(this)`, set pen/brush and draw. Request redraws with `update()` (never call `paintEvent`). A `QPainter` is valid only inside `paintEvent`; to draw offscreen paint onto a `QPixmap`/`QImage`." },
    { q: "How do you deploy a Qt C++ app?", a: "Run `windeployqt` / `macdeployqt` / `linuxdeployqt` (or CMake's `qt_generate_deploy_app_script`) to bundle Qt libs + **plugins** (`platforms/`) beside the binary, then wrap in a native installer and code-sign. Dynamic linking is LGPL-clean; static needs a commercial license. Test on a clean machine." }
  ],

  cheatsheet: [
    { label: "find + link Qt (CMake)", code: "find_package(Qt6 REQUIRED COMPONENTS Widgets)\ntarget_link_libraries(app PRIVATE Qt6::Widgets)" },
    { label: "Add executable", code: "qt_standard_project_setup()\nqt_add_executable(app main.cpp win.cpp win.h win.ui)" },
    { label: "Minimal app", code: "QApplication a(argc, argv); QWidget w; w.show(); return a.exec();" },
    { label: "Class needs meta-object", code: "class Foo : public QObject { Q_OBJECT ... };  // in a header" },
    { label: "Connect (modern)", code: "connect(btn, &QPushButton::clicked, this, &Win::onSave);" },
    { label: "Connect lambda", code: "connect(btn, &QPushButton::clicked, this, [this]{ n++; });" },
    { label: "Custom signal/slot", code: "signals: void done(int);  // emit: emit done(42);" },
    { label: "Parented child (no delete)", code: "auto *b = new QPushButton(\"OK\", this);" },
    { label: "Q_PROPERTY", code: "Q_PROPERTY(int n READ n WRITE setN NOTIFY nChanged)" },
    { label: "VBox + form layout", code: "auto *v=new QVBoxLayout(this); f->addRow(\"Name:\", edit); v->addLayout(f);" },
    { label: "QAction + shortcut", code: "auto *a=new QAction(\"&Save\",this); a->setShortcut(QKeySequence::Save);" },
    { label: "Message / file dialog", code: "QMessageBox::question(this,\"Q\",\"Sure?\",QMessageBox::Yes|QMessageBox::No);\nQFileDialog::getOpenFileName(this,\"Open\");" },
    { label: "Modal dialog", code: "if (dlg.exec() == QDialog::Accepted) { ... }" },
    { label: "Table model + proxy", code: "proxy->setSourceModel(model); view->setModel(proxy);" },
    { label: "Worker thread", code: "w->moveToThread(t); connect(t,&QThread::started,w,&Worker::run); t->start();" },
    { label: "QtConcurrent", code: "auto f = QtConcurrent::run([]{ return heavy(); });  // QFuture" },
    { label: "QTimer", code: "QTimer::singleShot(1000, this, [this]{ tick(); });" },
    { label: "Global QSS", code: "qApp->setStyleSheet(\"QPushButton:hover{background:#35b344;}\");" },
    { label: "Expose to QML", code: "class B:public QObject{Q_OBJECT QML_ELEMENT ...};" },
    { label: "Deploy", code: "windeployqt app.exe   # macdeployqt App.app -dmg" }
  ]
});
